import React, { useState, useEffect, useMemo } from 'react';
import { 
  Shield, Heart, Anchor, BookOpen, Scale, Zap, Sun, CloudRain, 
  Users, Flame, Info, Filter, Crosshair, Compass, Award, 
  AlertTriangle, Map, Wind, Lock, RotateCcw, Play, Check, X,
  Sparkles, MessageSquareQuote, Loader, Dices, Skull, Home, MapPin, Layers, Briefcase, Eye,
  CloudLightning, Book, Gamepad2, ChevronUp, Crown, Star, UserPlus,
  Clock, Gem, Wine, Frown, DoorOpen, GraduationCap, ShoppingCart, Coffee,
  Music, Plane, Footprints
} from 'lucide-react';

// --- CHARACTERS DATABASE ---
const CHARACTERS_DB = [
  { id: 'moses', name: 'Moses', title: 'The Meekest', ability: 'Lead the Way', desc: 'The first time you Move each turn costs 0 Action Points.', icon: <Wind /> },
  { id: 'ruth', name: 'Ruth', title: 'Loyal Companion', ability: 'Loyal Love', desc: 'You can Help players up to 3 nodes away (Standard is 1).', icon: <Heart /> },
  { id: 'david', name: 'David', title: 'Shepherd King', ability: 'Fearless', desc: 'Add +1 to the Faith Points generated by any Faith Action card.', icon: <Shield /> },
  { id: 'esther', name: 'Esther', title: 'Queen of Persia', ability: 'Royal Favor', desc: 'Draw 1 extra card from Provisions deck at end of turn.', icon: <Crown /> },
  { id: 'noah', name: 'Noah', title: 'Preacher', ability: 'Ark Builder', desc: 'Ignore effects from "Natural Disaster" Trial cards.', icon: <Anchor /> },
  { id: 'abraham', name: 'Abraham', title: 'Father of Faith', ability: 'Friend of God', desc: 'Prayer cards generate +1 extra Faith Point when played.', icon: <Star /> },
  { id: 'sarah', name: 'Sarah', title: 'Joyful Mother', ability: 'Laughter', desc: 'If Unity is 5 at start of turn, gain +1 Action Point.', icon: <Sun /> },
  { id: 'rahab', name: 'Rahab', title: 'Courageous', ability: 'Red Cord', desc: 'Gain +4 Faith Points when securing a Territory (Standard is +2).', icon: <MapPin /> },
  { id: 'gideon', name: 'Gideon', title: 'Mighty Warrior', ability: 'Cautious', desc: 'Once per turn, you may reroll the die on a Faith Action.', icon: <Dices /> },
  { id: 'daniel', name: 'Daniel', title: 'Beloved', ability: 'Integrity', desc: 'Ignore all negative effects from Personal Trial cards.', icon: <Lock /> },
  { id: 'peter', name: 'Peter', title: 'Rock', ability: 'Zeal', desc: 'Once per turn, move 2 nodes distance for 1 Action Point.', icon: <Flame /> },
  { id: 'paul', name: 'Paul', title: 'Apostle', ability: 'Missionary', desc: 'Draw 1 card immediately when entering a new Map Zone.', icon: <BookOpen /> },
];

// --- MAP GENERATION HELPERS ---

const generateConnections = (nodes) => {
  const connections = [];
  nodes.forEach((node) => {
    if (node.type === 'kingdom_hall') return;

    // Connect to neighbors in same zone (Lateral) - EXCEPT START NODES
    if (node.zone !== 0) {
      const sameZone = nodes.filter(n => n.zone === node.zone && n.id !== node.id);
      sameZone.sort((a, b) => {
        const diffA = Math.abs(a.angle - node.angle);
        const diffB = Math.abs(b.angle - node.angle);
        return Math.min(diffA, 360-diffA) - Math.min(diffB, 360-diffB);
      });
      sameZone.slice(0, 2).forEach(neighbor => {
         const linkId = [node.id, neighbor.id].sort().join('-');
         if (!connections.some(c => c.linkId === linkId)) {
           connections.push({ linkId, start: node.id, end: neighbor.id });
         }
      });
    }

    // Connect to inner zone
    const targetZone = node.zone === 0 ? 1 : node.zone === 1 ? 2 : node.zone === 2 ? 3 : 4;
    const innerCandidates = nodes.filter(n => n.zone === targetZone);
    innerCandidates.sort((a, b) => {
      const distA = Math.sqrt(Math.pow(a.x - node.x, 2) + Math.pow(a.y - node.y, 2));
      const distB = Math.sqrt(Math.pow(b.x - node.x, 2) + Math.pow(b.y - node.y, 2));
      return distA - distB;
    });

    if (innerCandidates.length > 0) {
      const target = innerCandidates[0];
      const linkId = [node.id, target.id].sort().join('-');
      if (!connections.some(c => c.linkId === linkId)) {
        connections.push({ linkId, start: node.id, end: target.id });
      }
    }
  });
  return connections;
};

const generateMap = () => {
  const nodes = [];
  
  const addNode = (id, type, zone, angleDeg, radius, label) => {
    const angleJitter = (Math.random() - 0.5) * 5; 
    const radiusJitter = (Math.random() - 0.5) * 2; 
    
    const angle = angleDeg + angleJitter;
    const r = radius + radiusJitter;

    const rad = angle * (Math.PI / 180);
    const x = 50 + r * Math.cos(rad);
    const y = 50 + r * Math.sin(rad);
    
    nodes.push({ id, type, zone, x, y, label, angle, r });
  };

  // 1. Center: Kingdom Hall (Zone 4)
  nodes.push({ id: 'kingdom_hall', type: 'kingdom_hall', zone: 4, x: 50, y: 50, label: 'Kingdom Hall', r: 0 });

  // 2. Zone 3: Inner Ring (8 Nodes)
  for (let i = 0; i < 8; i++) {
    addNode(`inner_${i}`, 'standard', 3, i * (360/8), 15, '');
  }

  // 3. Zone 2: Middle Ring (12 Nodes)
  const z2Count = 12;
  const territoryIndices = [0, 2, 5, 7, 10]; 
  for (let i = 0; i < z2Count; i++) {
    const isTerritory = territoryIndices.includes(i);
    const label = isTerritory ? `Territory ${territoryIndices.indexOf(i)+1}` : '';
    addNode(`mid_${i}`, isTerritory ? 'territory' : 'standard', 2, i * (360/z2Count), 28, label);
  }

  // 4. Zone 1: Outer Ring (20 Nodes) & Trap Nodes
  const z1Count = 20;
  const trapIndices = { 
    1: 'recreation',
    4: 'work', 
    10: 'school', 
    13: 'vacation',
    16: 'market' 
  };
  
  for (let i = 0; i < z1Count; i++) {
    const angle = i * (360/z1Count);
    if (trapIndices[i]) {
       const trapType = trapIndices[i];
       let label = 'Trap';
       if (trapType === 'work') label = 'Workplace';
       else if (trapType === 'school') label = 'University';
       else if (trapType === 'market') label = 'Supermarket';
       else if (trapType === 'recreation') label = 'Recreation';
       else if (trapType === 'vacation') label = 'Vacation';
       
       addNode(`trap_${trapType}`, 'trap', 1, angle, 42, label);
    } else {
       addNode(`outer_${i}`, 'standard', 1, angle, 38, '');
    }
  }

  // 5. Zone 0: Start Nodes (4 Fixed Positions)
  const startAngles = [90, 180, 270, 0];
  startAngles.forEach((angle, i) => {
    const rad = angle * (Math.PI / 180);
    const x = 50 + 48 * Math.cos(rad);
    const y = 50 + 48 * Math.sin(rad);
    nodes.push({ id: `start_${i}`, type: 'start', zone: 0, x, y, label: `Start ${i+1}`, r: 48 });
  });

  const connections = generateConnections(nodes);
  return { nodes, connections };
};

const { nodes: NODES, connections: CONNECTIONS } = generateMap();

// --- DATA POOLS ---

const SHUFFLE = (array) => {
  let currentIndex = array.length, randomIndex;
  while (currentIndex !== 0) {
    randomIndex = Math.floor(Math.random() * currentIndex);
    currentIndex--;
    [array[currentIndex], array[randomIndex]] = [array[randomIndex], array[currentIndex]];
  }
  return array;
};

const CHALLENGE_POOL = [
  { title: 'Economic Crisis', type: 'Challenge', req: 15, penalty: 'Unity -1', desc: 'Inflation strikes. Resources are scarce.' },
  { title: 'Direct Opposition', type: 'Challenge', req: 20, penalty: 'Discard 1 Card', desc: 'Preaching work is restricted.' },
  { title: 'Natural Disaster', type: 'Challenge', req: 18, penalty: 'Cannot Move 1 Turn', desc: 'Flooding in the area blocks paths.' },
  { title: 'Congregation Dispute', type: 'Challenge', req: 12, penalty: 'Unity -2', desc: 'Misunderstandings cause friction.' },
  { title: 'Family Opposition', type: 'Challenge', req: 14, penalty: 'AP -1 for 2 Turns', desc: 'Relatives pressure a player to stop.' },
  { title: 'Health Emergency', type: 'Challenge', req: 16, penalty: 'Random Player Frozen', desc: 'A sudden illness strikes.' },
];

const CIRCUMSTANCE_POOL = [
  { title: 'Heavy Rains', type: 'Circumstance', effect: 'Move Cost +1', desc: 'Roads are muddy. Moving costs 2 AP.' },
  { title: 'Digital Surveillance', type: 'Circumstance', effect: 'No Trivia Bonus', desc: 'Communication is monitored. Trivia disabled.' },
  { title: 'Heatwave', type: 'Circumstance', effect: 'AP Max = 2', desc: 'Exhaustion sets in quickly. Max 2 AP.' },
  { title: 'Transportation Strike', type: 'Circumstance', effect: 'Range = 0', desc: 'No public transport. Cannot help from distance.' },
  { title: 'Distractions', type: 'Circumstance', effect: 'Hand Limit -1', desc: 'Worldly entertainment distracts. Hold 1 less card.' },
];

const SUPPLY_POOL = [
  { type: 'FaithAction', title: 'Bold Witness', icon: <Flame />, points: 2, bonus: 5, question: 'Who spoke to the burning bush?', answer: 'Moses' },
  { type: 'FaithAction', title: 'Defend Faith', icon: <Shield />, points: 2, bonus: 5, question: 'Which apostle walked on water briefly?', answer: 'Peter' },
  { type: 'Prayer', title: 'Prayer for Wisdom', icon: <Sparkles />, points: 3, effect: 'Wildcard: +3 Points' },
  { type: 'Prayer', title: 'Prayer for Courage', icon: <Zap />, points: 3, effect: 'Wildcard: Free Move' },
  { type: 'Quality', title: 'Loyal Love', icon: <Heart />, points: 0, effect: 'Active: Helping Range +1.' },
  { type: 'Quality', title: 'Mildness', icon: <Wind />, points: 0, effect: 'Active: Ignore "Dispute" penalties.' },
  { type: 'Trial', title: 'Doubt', icon: <CloudRain />, points: -2, effect: 'Burden: Cannot use Bonus Points.' },
  { type: 'Trial', title: 'Anxiety', icon: <AlertTriangle />, points: -1, effect: 'Burden: Movement costs 2 AP.' },
  { type: 'Trial', title: 'Unwise Use of Time', icon: <Clock />, points: -1, effect: 'Burden: Max 2 AP per turn. Discard 1 card to remove.' },
  { type: 'Trial', title: 'Showy Display', icon: <Gem />, points: -1, effect: 'Burden: Territory bonuses are disabled for you.' },
  { type: 'Trial', title: 'Bad Associations', icon: <Users />, points: -2, effect: 'Burden: You cannot use the Help action.' },
  { type: 'Trial', title: 'Overdrinking', icon: <Wine />, points: -1, effect: 'Burden: Start next turn with -1 AP.' },
  { type: 'Trial', title: 'Materialism', icon: <Frown />, points: -1, effect: 'Burden: Move 1 Zone Outward if possible at start of turn.' },
  { type: 'Obligation', title: 'Overtime Shift', icon: <Briefcase />, targetNode: 'trap_work', desc: 'Teleport to Workplace. Turn Ends.' },
  { type: 'Obligation', title: 'Final Exams', icon: <GraduationCap />, targetNode: 'trap_school', desc: 'Teleport to University. Turn Ends.' },
  { type: 'Obligation', title: 'Grocery Run', icon: <ShoppingCart />, targetNode: 'trap_market', desc: 'Teleport to Supermarket. Turn Ends.' },
  { type: 'Obligation', title: 'Recreation Time', icon: <Music />, targetNode: 'trap_recreation', desc: 'Teleport to Recreation. Leaving reduces Faith Progress.' },
  { type: 'Obligation', title: 'Vacation Trip', icon: <Plane />, targetNode: 'trap_vacation', desc: 'Teleport to Vacation. Next Territory move costs +1 AP.' },
];

const BUILD_DECKS = () => {
  let challenges = SHUFFLE([...CHALLENGE_POOL, ...CHALLENGE_POOL]); 
  const gtCard = { title: 'Great Tribulation', type: 'Event', effect: 'SCATTER', desc: 'Max Active Characters = 2. Territories become Inner Rooms. Map changes.' };
  const midIndex = Math.floor(challenges.length / 2);
  challenges.splice(midIndex + Math.floor(Math.random() * 3), 0, gtCard);
  const armageddon = { title: 'Armageddon', type: 'Challenge', req: 40, penalty: 'GAME OVER', desc: 'Activate ALL Characters. Stand Firm!' };
  const trialDeck = [...challenges.slice(0, 10), armageddon];

  let circumstances = [];
  for (let i=0; i<3; i++) circumstances = [...circumstances, ...CIRCUMSTANCE_POOL];
  const circumstanceDeck = SHUFFLE(circumstances);

  let supplyDeck = [];
  for (let i = 0; i < 4; i++) { supplyDeck = [...supplyDeck, ...SUPPLY_POOL]; }
  
  CHARACTERS_DB.forEach(char => {
    supplyDeck.push({ type: 'Character', ...char });
  });

  supplyDeck = SHUFFLE(supplyDeck).map((c, i) => ({...c, id: `sup_${i}`, uniqueId: Math.random().toString(36)}));

  return { trialDeck, circumstanceDeck, supplyDeck };
};

const getDistance = (startId, endId, connections) => {
  if (startId === endId) return 0;
  const connected = connections.some(c => (c.start === startId && c.end === endId) || (c.start === endId && c.end === startId));
  if (connected) return 1;
  return 999;
};

// --- COMPONENTS ---

const Card = ({ data, isSelected, onClick, isFaceUp = true, size = 'sm', showEffects = true }) => {
  if (!data) return <div className="w-16 h-24 bg-zinc-800 rounded border border-zinc-700 opacity-20"></div>;

  const width = size === 'xs' ? 'w-10' : size === 'md' ? 'w-20' : size === 'lg' ? 'w-24' : size === 'xl' ? 'w-64' : 'w-14';
  const height = size === 'xs' ? 'h-14' : size === 'md' ? 'h-32' : size === 'lg' ? 'h-40' : size === 'xl' ? 'h-96' : 'h-20';
  
  let textSizeTitle = 'text-[6px]';
  let textSizeBody = 'text-[5px]';
  let iconSize = 8;

  if (size === 'md') { textSizeTitle = 'text-[9px]'; textSizeBody = 'text-[7px]'; iconSize = 14; }
  if (size === 'lg') { textSizeTitle = 'text-[10px]'; textSizeBody = 'text-[8px]'; iconSize = 16; }
  if (size === 'xl') { textSizeTitle = 'text-xl'; textSizeBody = 'text-sm'; iconSize = 32; }

  if (!isFaceUp) {
    let backColor = 'bg-indigo-950 border-indigo-900';
    let BackIcon = Crosshair;
    if (data === 'trial_back') { backColor = 'bg-red-950 border-red-900'; BackIcon = Skull; }
    if (data === 'circumstance_back') { backColor = 'bg-slate-800 border-slate-700'; BackIcon = Layers; }

    return (
      <div onClick={onClick} className={`${width} ${height} ${backColor} rounded border flex items-center justify-center shadow-lg bg-[url('https://www.transparenttextures.com/patterns/cubes.png')] cursor-pointer hover:brightness-110 transition-transform active:scale-95`}>
        <BackIcon className={`w-8 h-8 ${data === 'trial_back' ? 'text-red-800' : data === 'circumstance_back' ? 'text-slate-600' : 'text-indigo-300'}`} />
      </div>
    );
  }

  const isAdversary = data.type === 'Challenge' || data.type === 'Event';
  const isCircumstance = data.type === 'Circumstance';
  const isTrial = data.type === 'Trial' || data.type === 'Obligation';
  const isPrayer = data.type === 'Prayer';
  const isCharacter = data.type === 'Character';
  
  let baseColor = 'bg-indigo-700';
  if (isAdversary) baseColor = 'bg-red-900';
  if (isCircumstance) baseColor = 'bg-slate-600';
  if (isTrial) baseColor = 'bg-zinc-800 border-red-500/50';
  if (isCharacter) baseColor = 'bg-amber-600 border-amber-400';

  const borderColor = isSelected 
    ? 'border-amber-400 ring-2 ring-amber-400' 
    : isPrayer || isCharacter ? 'border-amber-200/50 shadow-[0_0_10px_rgba(251,191,36,0.3)]' : 'border-zinc-600';

  const renderIcon = () => {
    if (React.isValidElement(data.icon)) {
      return React.cloneElement(data.icon, { size: iconSize, className: "text-white" });
    }
    return <Info size={iconSize} className="text-white" />;
  };

  return (
    <div onClick={onClick} className={`relative ${width} ${height} rounded-lg shadow-xl flex flex-col overflow-hidden transition-all duration-200 border ${borderColor} ${isSelected ? '-translate-y-2 z-50' : 'hover:-translate-y-1'}`}>
      <div className={`${baseColor} ${size === 'xl' ? 'h-16 p-4' : 'h-6 p-1.5'} flex justify-between items-center`}>
        <span className={`${textSizeTitle} font-bold text-white uppercase opacity-80 truncate`}>{data.type ? data.type.slice(0,10) : 'CARD'}</span>
        {renderIcon()}
      </div>
      <div className="bg-white flex-grow p-2 flex flex-col relative">
        <p className={`${textSizeTitle} font-bold leading-tight text-zinc-900 mb-2`}>{data.name || data.title}</p>
        <p className={`${textSizeBody} text-zinc-600 leading-tight`}>{data.desc || data.question || data.effect || data.ability}</p>
        {showEffects && data.points !== undefined && (
          <div className={`mt-auto self-end px-2 py-1 rounded ${textSizeBody} font-bold border ${data.points < 0 ? 'bg-red-100 text-red-700 border-red-200' : 'bg-emerald-50 text-emerald-700 border-emerald-100'}`}>
            {data.points > 0 ? '+' : ''}{data.points}
          </div>
        )}
      </div>
    </div>
  );
};

const NodeMap = ({ players, nodes, connections, onNodeClick, validMoves }) => {
  return (
    <div className="absolute inset-0 z-0">
      <svg className="w-full h-full pointer-events-none z-0">
        {connections.map((c, i) => {
          const sNode = nodes.find(n => n.id === c.start);
          const eNode = nodes.find(n => n.id === c.end);
          if (!sNode || !eNode) return null;
          return <line key={i} x1={`${sNode.x}%`} y1={`${sNode.y}%`} x2={`${eNode.x}%`} y2={`${eNode.y}%`} className="stroke-zinc-600/60 stroke-[0.8]" />;
        })}
      </svg>
      {nodes.map(node => {
        const occupants = players.filter(p => p.nodeId === node.id);
        const isValidMove = validMoves.includes(node.id);
        const isSpecial = node.type === 'kingdom_hall' || node.type === 'territory';
        const isTrap = node.type === 'trap';
        const isInnerRoom = node.type === 'inner_room';
        const isStart = node.type === 'start';
        
        let nodeSize = 'w-1.5 h-1.5';
        let nodeColor = 'bg-zinc-700';
        
        if (node.type === 'kingdom_hall') { nodeSize = 'w-6 h-6'; nodeColor = 'bg-amber-500 shadow-[0_0_20px_rgba(245,158,11,0.5)]'; }
        else if (node.type === 'territory') { nodeSize = 'w-3 h-3'; nodeColor = 'bg-indigo-500 shadow-[0_0_10px_rgba(99,102,241,0.5)]'; }
        else if (node.type === 'trap') { nodeSize = 'w-4 h-4'; nodeColor = 'bg-red-900 border border-red-600 shadow-[0_0_15px_rgba(220,38,38,0.6)]'; }
        else if (node.type === 'inner_room') { nodeSize = 'w-4 h-4'; nodeColor = 'bg-purple-600 border border-purple-400 shadow-[0_0_15px_rgba(147,51,234,0.6)]'; }
        else if (node.type === 'start') { nodeSize = 'w-3 h-3'; nodeColor = isValidMove ? 'bg-zinc-500 border border-white' : 'bg-zinc-800 border border-zinc-600'; }
        
        // Trap specific icons
        let TrapIcon = Briefcase;
        if (node.id === 'trap_school') TrapIcon = GraduationCap;
        if (node.id === 'trap_market') TrapIcon = ShoppingCart;
        if (node.id === 'trap_recreation') TrapIcon = Music;
        if (node.id === 'trap_vacation') TrapIcon = Plane;

        // Determine click handler: If valid move, just move (existing logic). 
        // If not valid but special, open inspector.
        const isClickable = isValidMove || isSpecial || isTrap || isInnerRoom || isStart;
        
        // Visual indicator for special nodes that are not valid moves (inspectable)
        const canInspect = !isValidMove && (isSpecial || isTrap || isInnerRoom || isStart);
        const ringClass = canInspect ? 'ring-1 ring-zinc-500/50' : '';

        return (
          <div key={node.id} onClick={() => isClickable && onNodeClick(node.id)} className={`absolute -translate-x-1/2 -translate-y-1/2 transition-all duration-300 ${isClickable ? 'cursor-pointer' : 'pointer-events-none'} ${isValidMove ? 'scale-125 z-20' : 'z-10'}`} style={{ left: `${node.x}%`, top: `${node.y}%` }}>
            <div className={`${isValidMove ? 'w-8 h-8 -m-2' : 'w-4 h-4'} absolute flex items-center justify-center`}>
                <div className={`${nodeSize} rounded-full ${nodeColor} ${isValidMove ? 'animate-pulse ring-2 ring-emerald-400' : ringClass} flex items-center justify-center transition-all`}>
                    {node.type === 'kingdom_hall' && <Home size={12} className="text-zinc-900" />}
                    {isInnerRoom && <DoorOpen size={10} className="text-white" />}
                    {isTrap && <TrapIcon size={8} className="text-white" />}
                </div>
            </div>
            {(isSpecial || isStart || isInnerRoom || isTrap) && <div className="absolute top-3 left-1/2 -translate-x-1/2 text-[10px] font-bold text-zinc-400 whitespace-nowrap uppercase tracking-wider bg-zinc-950/80 px-2 py-0.5 rounded pointer-events-none border border-zinc-800 shadow-md">{node.label}</div>}
            <div className="absolute inset-0 flex items-center justify-center pointer-events-none">
               {occupants.map((p, i) => (
                 <div key={p.id} className="w-4 h-4 rounded-full border border-white text-[6px] font-bold flex items-center justify-center shadow-md absolute transition-all" style={{ backgroundColor: p.color, transform: `translate(${i * 4}px, ${i * -4}px)`, zIndex: 30 + i }}>{p.activeCharacters[0]?.name?.charAt(0) || 'P'}</div>
               ))}
            </div>
          </div>
        );
      })}
    </div>
  );
};

const PlayerHand = ({ player, isActive, rotation, onCardClick, toggleHand, isOpen }) => {
  const getStyle = () => {
    const common = { position: 'absolute', transition: 'transform 0.5s cubic-bezier(0.34, 1.56, 0.64, 1)', zIndex: 50 };
    if (rotation === 0) return { ...common, bottom: 0, left: '50%', transform: `translateX(-50%) translateY(${isOpen ? '0' : 'calc(100% - 3rem)'})` };
    if (rotation === 1) return { ...common, top: '50%', left: 0, transformOrigin: 'top left', transform: `rotate(90deg) translateX(-50%) translateY(${isOpen ? '-100%' : '-3rem'})` };
    if (rotation === 2) return { ...common, top: 0, left: '50%', transform: `translateX(-50%) rotate(180deg) translateY(${isOpen ? '0' : 'calc(100% - 3rem)'})` };
    if (rotation === 3) return { ...common, top: '50%', right: 0, transformOrigin: 'top right', transform: `rotate(-90deg) translateX(50%) translateY(${isOpen ? '-100%' : '-3rem'})` };
    return {};
  };

  const primaryChar = player.activeCharacters[0];

  return (
    <div style={getStyle()}>
       <div className={`flex flex-col items-center w-[20rem]`}> 
         <button onClick={toggleHand} className={`w-full h-12 rounded-t-xl font-bold shadow-[0_-4px_10px_rgba(0,0,0,0.5)] border-t border-x border-zinc-700 bg-zinc-900 text-white flex items-center justify-center gap-2 cursor-pointer transition-colors ${isActive ? 'ring-2 ring-amber-500 text-amber-500' : 'text-zinc-400 hover:text-white hover:bg-zinc-800'}`}>
           {isOpen ? <ChevronUp className="rotate-180 transition-transform" size={16}/> : <ChevronUp size={16}/>}
           <span className="truncate">{primaryChar ? primaryChar.name : `P${player.id+1}`}</span>
           <span className="text-[10px] bg-zinc-800 px-1.5 rounded-full">{player.hand.length}</span>
         </button>
         <div className="bg-zinc-900/95 backdrop-blur-xl border-t border-zinc-700 p-4 pb-8 rounded-b-2xl shadow-2xl w-full flex justify-center min-h-[160px]">
            <div className="flex -space-x-8 hover:space-x-1 transition-all duration-300 items-end h-32">
              {player.hand.map((c, i) => (
                <div key={c.uniqueId} className="origin-bottom transition-transform hover:-translate-y-6" style={{ zIndex: i }}>
                  <Card data={c} size="md" onClick={() => onCardClick(c)} isSelected={false} />
                </div>
              ))}
              {player.hand.length === 0 && <span className="text-xs text-zinc-600 font-bold uppercase py-8">Empty</span>}
            </div>
         </div>
       </div>
    </div>
  );
};

const CardInspectionModal = ({ card, onClose, onPlay, canPlay, isPlayerTurn }) => {
  return (
    <div className="absolute inset-0 z-[200] flex items-center justify-center bg-black/90 backdrop-blur-md p-8 animate-in fade-in zoom-in duration-200" onClick={onClose}>
      <div className="relative flex flex-col items-center gap-6" onClick={(e) => e.stopPropagation()}>
        <div className="transform scale-110 shadow-[0_0_50px_rgba(0,0,0,0.8)]"><Card data={card} isFaceUp={true} size="xl" showEffects={true} /></div>
        <div className="flex flex-col gap-3 w-full max-w-xs">
           {(canPlay && isPlayerTurn) ? (
             <button onClick={onPlay} className="w-full py-4 bg-emerald-600 hover:bg-emerald-500 text-white font-black text-xl rounded-xl shadow-lg transform transition-all active:scale-95 flex items-center justify-center gap-2"><Play className="fill-current" /> PLAY CARD</button>
           ) : (
             <div className="bg-zinc-800 text-zinc-500 font-bold text-center py-3 rounded-xl border border-zinc-700">{isPlayerTurn ? "Cannot Play This Card" : "Waiting for Turn..."}</div>
           )}
           <button onClick={onClose} className="text-zinc-400 font-bold hover:text-white mt-2">Close Inspection</button>
        </div>
      </div>
    </div>
  );
};

const TriviaModal = ({ card, onClose, onResult }) => {
  const [step, setStep] = useState('roll'); 
  const [roll, setRoll] = useState(0);
  const difficulty = roll > 3 ? 'Hard' : 'Easy';
  const handleRoll = () => { const r = Math.floor(Math.random() * 6) + 1; setRoll(r); setStep('question'); };

  return (
    <div className="absolute inset-0 z-[250] flex items-center justify-center bg-black/95 backdrop-blur-md p-4 animate-in fade-in">
      <div className="bg-zinc-900 border border-amber-500/50 rounded-2xl max-w-sm w-full p-6 shadow-2xl relative overflow-hidden">
        <h3 className="text-xl font-black text-amber-500 uppercase italic mb-4 flex items-center gap-2">Faith in Action</h3>
        {step === 'roll' && <div className="text-center space-y-6"><button onClick={handleRoll} className="bg-amber-500 text-zinc-900 font-bold px-8 py-4 rounded-xl flex items-center gap-2 mx-auto"><Dices /> Roll Dice</button></div>}
        {step === 'question' && (
          <div className="space-y-4">
            <div className="flex justify-between items-center text-xs font-bold text-zinc-500 border-b border-zinc-800 pb-2"><span>Rolled: {roll}</span><span>{difficulty}</span></div>
            <p className="text-white font-serif text-lg py-4">"{card.question}"</p>
            <div className="grid grid-cols-2 gap-3">
              <button onClick={() => onResult(false)} className="py-3 rounded bg-zinc-800 text-zinc-400 font-bold">Skip</button>
              <button onClick={() => onResult(true)} className="py-3 rounded bg-emerald-600 text-white font-bold">Correct</button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

// --- NEW NODE INSPECTION MODAL ---
const NodeInspectionModal = ({ node, onClose, onTravel, canTravel, travelCost }) => {
  let title = node.label || 'Unknown Location';
  let desc = 'A normal location on the map.';
  let typeLabel = 'Standard Node';
  let effect = null;
  let icon = <MapPin size={32} className="text-zinc-500" />;
  let color = "text-zinc-400";

  if (node.type === 'kingdom_hall') {
    title = 'Kingdom Hall';
    typeLabel = 'Sanctuary';
    desc = 'The center of spiritual safety and the ultimate destination for the group.';
    effect = { type: 'positive', text: '+5 Faith Points when secured.' };
    icon = <Home size={32} className="text-amber-500" />;
    color = "text-amber-500";
  } else if (node.type === 'territory') {
    typeLabel = 'Territory';
    desc = 'An unassigned territory ripe for the harvest.';
    effect = { type: 'positive', text: '+2 Faith Points when secured.' };
    icon = <MapPin size={32} className="text-indigo-500" />;
    color = "text-indigo-500";
  } else if (node.type === 'trap') {
    typeLabel = 'Distraction';
    color = "text-red-500";
    if (node.id === 'trap_work') {
      title = 'Workplace';
      desc = 'Mandatory overtime consumes your energy.';
      effect = { type: 'negative', text: 'Cost 2 AP to leave this node.' };
      icon = <Briefcase size={32} className="text-red-500" />;
    } else if (node.id === 'trap_school') {
      title = 'University';
      desc = 'Intense studies require focus.';
      effect = { type: 'negative', text: 'Cost 2 AP to leave this node.' };
      icon = <GraduationCap size={32} className="text-red-500" />;
    } else if (node.id === 'trap_market') {
      title = 'Supermarket';
      desc = 'The cares of daily life.';
      effect = { type: 'negative', text: 'Cost 2 AP to leave this node.' };
      icon = <ShoppingCart size={32} className="text-red-500" />;
    } else if (node.id === 'trap_recreation') {
      title = 'Recreation';
      desc = 'Entertainment can be refreshing but distracting.';
      effect = { type: 'negative', text: 'Leaving drains 2 Faith Points from progress.' };
      icon = <Music size={32} className="text-amber-500" />;
      color = "text-amber-500";
    } else if (node.id === 'trap_vacation') {
      title = 'Vacation';
      desc = 'A time to relax, but re-engaging takes effort.';
      effect = { type: 'negative', text: 'Next Territory secure costs +1 AP.' };
      icon = <Plane size={32} className="text-blue-400" />;
      color = "text-blue-400";
    }
  } else if (node.type === 'inner_room') {
    title = 'Inner Room';
    typeLabel = 'Refuge';
    desc = 'A safe house during the Great Tribulation.';
    effect = { type: 'positive', text: 'Safe from most trials. Limited capacity.' };
    icon = <DoorOpen size={32} className="text-purple-500" />;
    color = "text-purple-500";
  } else if (node.type === 'start') {
    typeLabel = 'Start Zone';
    desc = 'Where your journey begins.';
    icon = <Footprints size={32} className="text-zinc-500" />;
  }

  return (
    <div className="absolute inset-0 z-[200] flex items-center justify-center bg-black/90 backdrop-blur-md p-8 animate-in fade-in zoom-in duration-200" onClick={onClose}>
      <div className="bg-zinc-900 border border-zinc-700 rounded-2xl p-6 shadow-2xl max-w-sm w-full relative" onClick={(e) => e.stopPropagation()}>
        <button onClick={onClose} className="absolute top-4 right-4 text-zinc-500 hover:text-white"><X size={20} /></button>
        
        <div className="flex flex-col items-center text-center mb-6">
           <div className={`p-4 rounded-full bg-zinc-800 mb-4 ${color} shadow-lg ring-1 ring-white/10`}>{icon}</div>
           <div className={`text-xs font-bold uppercase tracking-widest mb-1 ${color}`}>{typeLabel}</div>
           <h2 className="text-2xl font-black text-white mb-2">{title}</h2>
           <p className="text-sm text-zinc-400 leading-relaxed">{desc}</p>
        </div>

        {effect && (
          <div className={`mb-6 p-3 rounded-lg border flex items-start gap-3 text-left ${effect.type === 'positive' ? 'bg-emerald-900/20 border-emerald-500/50' : 'bg-red-900/20 border-red-500/50'}`}>
             {effect.type === 'positive' ? <Check size={16} className="text-emerald-500 mt-0.5" /> : <AlertTriangle size={16} className="text-red-500 mt-0.5" />}
             <div>
               <div className={`text-xs font-bold uppercase ${effect.type === 'positive' ? 'text-emerald-400' : 'text-red-400'}`}>Effect</div>
               <div className="text-xs text-zinc-300">{effect.text}</div>
             </div>
          </div>
        )}

        {canTravel ? (
          <button onClick={onTravel} className="w-full py-3 bg-emerald-600 hover:bg-emerald-500 text-white font-bold rounded-xl shadow-lg flex items-center justify-center gap-2">
            <Footprints size={18} /> Travel Here ({travelCost} AP)
          </button>
        ) : (
          <div className="w-full py-3 bg-zinc-800 text-zinc-500 font-bold rounded-xl text-center text-sm">
            {node.type === 'kingdom_hall' ? 'Too Far to Travel' : 'Too Far / Not Enough AP'}
          </div>
        )}
      </div>
    </div>
  );
};

// ... ManualView ...
const ManualView = () => (
  <div className="w-full h-full overflow-y-auto bg-zinc-900 text-zinc-300 p-8 pt-24 pb-20 font-sans selection:bg-indigo-500 selection:text-white animate-in fade-in">
    <div className="max-w-3xl mx-auto space-y-8">
      <div className="text-center border-b border-zinc-800 pb-8"><h1 className="text-4xl font-black text-white tracking-tight mb-2 uppercase">Covenant & Kingdom</h1><p className="text-amber-500 font-bold uppercase tracking-widest text-xs">Official Field Guide</p></div>
      <section><h2 className="text-2xl font-bold text-white mb-4 flex items-center gap-2"><Compass className="text-indigo-500" /> The Mission</h2><p className="leading-relaxed mb-4 text-sm md:text-base">Stand Firm & Gather Together.</p></section>
    </div>
  </div>
);

// --- MAIN GAME CONTAINER ---

export default function TacticalGame() {
  const [activeTab, setActiveTab] = useState('game'); 
  const [gameState, setGameState] = useState('setup');
  const [roundPhase, setRoundPhase] = useState('START'); 
  const [turnIndex, setTurnIndex] = useState(0);
  const [actionPoints, setActionPoints] = useState(3);
  const [maxCharacters, setMaxCharacters] = useState(1);
  const [hasMoved, setHasMoved] = useState(false);
  
  const [mapNodes, setMapNodes] = useState([]);
  const [mapConnections, setMapConnections] = useState([]);
  
  const [players, setPlayers] = useState([]);
  const [supplyDeck, setSupplyDeck] = useState([]);
  const [trialDeck, setTrialDeck] = useState([]);
  const [circumstanceDeck, setCircumstanceDeck] = useState([]);
  
  const [currentChallenge, setCurrentChallenge] = useState(null);
  const [currentCircumstance, setCurrentCircumstance] = useState(null);
  const [challengeProgress, setChallengeProgress] = useState(0);
  const [unity, setUnity] = useState(5);

  const [inspectingCard, setInspectingCard] = useState(null);
  const [inspectingNode, setInspectingNode] = useState(null); // NEW: Track inspecting node
  const [selectedCard, setSelectedCard] = useState(null); 
  const [showTrivia, setShowTrivia] = useState(false);
  const [notification, setNotification] = useState(null);
  const [openHandIndex, setOpenHandIndex] = useState(null);

  const startGame = (numPlayers) => {
    const colors = ['#3b82f6', '#ef4444', '#10b981', '#f59e0b'];
    const shuffledChars = SHUFFLE([...CHARACTERS_DB]);
    
    const initialMap = generateMap(); 
    setMapNodes(initialMap.nodes);
    setMapConnections(initialMap.connections);

    const newPlayers = Array.from({ length: numPlayers }, (_, i) => ({
      id: i,
      color: colors[i % colors.length],
      nodeId: `start_${i}`, 
      visitedSpecials: [], 
      hand: [],
      activeCards: [],
      activeCharacters: [shuffledChars[i]],
      vacationPenalty: false 
    }));
    
    const { trialDeck, circumstanceDeck, supplyDeck } = BUILD_DECKS();
    
    let starterCandidates = supplyDeck.filter(c => c.type !== 'Trial' && c.type !== 'Character' && c.type !== 'Obligation');
    let restrictedCards = supplyDeck.filter(c => c.type === 'Trial' || c.type === 'Character' || c.type === 'Obligation');
    
    newPlayers.forEach(p => { 
       p.hand = starterCandidates.splice(0, 3);
    });

    const finalSupplyDeck = SHUFFLE([...starterCandidates, ...restrictedCards]);

    setPlayers(newPlayers);
    setSupplyDeck(finalSupplyDeck);
    setTrialDeck(trialDeck);
    setCircumstanceDeck(circumstanceDeck);
    setGameState('playing');
  };
  
  const triggerGreatTribulation = () => {
    const newNodes = mapNodes.map(n => {
      if (n.type === 'territory') {
        return { ...n, type: 'inner_room', label: 'Inner Room' };
      }
      return n;
    });

    const occupiedIds = new Set(players.map(p => p.nodeId));
    
    const filteredNodes = newNodes.filter(n => {
      if (n.type === 'standard' && (n.zone === 1 || n.zone === 2)) {
        if (occupiedIds.has(n.id)) return true; 
        return Math.random() > 0.4; 
      }
      return true; 
    });

    const newConnections = generateConnections(filteredNodes);

    setMapNodes(filteredNodes);
    setMapConnections(newConnections);
    setMaxCharacters(2);
    showNotification("GREAT TRIBULATION! Map Changed!", "purple");
  };

  const startRound = () => {
    if (trialDeck.length === 0) {
      showNotification("VICTORY!", "emerald");
      return;
    }
    const advCard = trialDeck[0];
    setCurrentChallenge({ ...advCard, progress: 0 });
    
    let circ = null;
    if (circumstanceDeck.length > 0) circ = circumstanceDeck[0];
    setCurrentCircumstance(circ);
    
    if (advCard.type === 'Event' && advCard.title === 'Great Tribulation') {
      triggerGreatTribulation();
    } else if (advCard.title === 'Armageddon') {
      setMaxCharacters(99);
      showNotification("Armageddon: Activate ALL!", "red");
    } else {
      const hasInner = mapNodes.some(n => n.type === 'inner_room');
      setMaxCharacters(hasInner ? 2 : 1);
    }

    setRoundPhase('ACTION');
    setActionPoints(3);
    setTurnIndex(0);
    setHasMoved(false);
  };

  useEffect(() => {
    if (gameState === 'playing' && roundPhase === 'START' && trialDeck.length > 0 && !currentChallenge) {
      startRound();
    }
  }, [gameState, roundPhase, trialDeck, currentChallenge]);

  // UNIFIED NODE CLICK HANDLER
  const handleNodeInteraction = (targetNodeId) => {
    setOpenHandIndex(null);
    const currentPlayer = players[turnIndex];
    const dist = getDistance(currentPlayer.nodeId, targetNodeId, mapConnections);
    const targetNode = mapNodes.find(n => n.id === targetNodeId);
    
    // Check Traps on Current Node to determine cost
    const currentNode = mapNodes.find(n => n.id === currentPlayer.nodeId);
    let cost = 1;
    if (currentNode && currentNode.type === 'trap') {
       if (currentNode.id === 'trap_recreation' || currentNode.id === 'trap_vacation') {
         cost = 1;
       } else {
         cost = 2; // Work/School/Market
       }
    }
    if (!hasMoved && currentPlayer.activeCharacters.some(c => c.id === 'moses')) cost = 0;

    const isValidMove = (dist === 1 && actionPoints >= cost);

    // If it's a Special Node (even if valid move), open Inspector first? 
    // Or if it's a VALID move to a standard node, just move?
    // Let's implement: Click = Inspect/Move Prompt for ALL nodes to be consistent, OR
    // Click Special = Inspect. Click Standard = Move.
    // The user asked to "make special nodes clickable to reveal effects".
    // Let's open the modal for ANY special node click.
    const isSpecial = targetNode.type === 'kingdom_hall' || targetNode.type === 'territory' || targetNode.type === 'trap' || targetNode.type === 'inner_room' || targetNode.type === 'start';
    
    if (isSpecial) {
       setInspectingNode({ ...targetNode, canTravel: isValidMove, travelCost: cost });
    } else {
       // Standard node: Just move if valid
       if (isValidMove) executeMove(targetNodeId, cost);
    }
  };

  const executeMove = (targetNodeId, cost) => {
    setInspectingNode(null);
    const currentPlayer = players[turnIndex];
    const updatedPlayers = [...players];
    updatedPlayers[turnIndex].nodeId = targetNodeId;
    
    const targetNode = mapNodes.find(n => n.id === targetNodeId);

    // Trap Exit Effects
    const currentNode = mapNodes.find(n => n.id === players[turnIndex].nodeId);
    if (currentNode && currentNode.id === 'trap_recreation') {
        setChallengeProgress(prev => Math.max(0, prev - 2));
        showNotification("Distracted! -2 Faith Pts", "amber");
    }
    if (currentNode && currentNode.id === 'trap_vacation') {
        updatedPlayers[turnIndex].vacationPenalty = true;
        showNotification("Vacation Lag Applied", "blue");
    }

    // Inner Room Cap
    if (targetNode.type === 'inner_room') {
       const occupants = players.filter(p => p.nodeId === targetNodeId).length;
       const limit = players.length >= 4 ? 3 : 2;
       if (occupants >= limit) {
         showNotification("Room Full! Cannot Enter.", "red");
         return;
       }
    }

    // Rahab / Points / Penalties
    if (targetNode.type === 'territory' || targetNode.type === 'kingdom_hall') {
        let points = targetNode.type === 'kingdom_hall' ? 5 : 2;
        
        // Vacation Penalty Check
        if (targetNode.type === 'territory' && currentPlayer.vacationPenalty) {
             // If we didn't pay extra cost, we can't secure it?
             // Or cost was handled in AP check?
             // Current logic: Penalty increases AP cost.
             // We need to verify AP here if penalty active.
             // Simplification: Penalty adds 1 to cost.
             // If we are here, we paid `cost`.
             if (currentPlayer.vacationPenalty) {
                 // Double check AP
                 if (actionPoints < cost + 1) { // Assuming cost was 1, needs 2
                    showNotification("Sluggish! Need more AP.", "red");
                    return;
                 }
                 // Pay extra
                 cost += 1;
                 updatedPlayers[turnIndex].vacationPenalty = false;
                 showNotification("Vacation Lag Cleared", "blue");
             }
        }

        if (!updatedPlayers[turnIndex].visitedSpecials.includes(targetNodeId)) {
          updatedPlayers[turnIndex].visitedSpecials.push(targetNodeId);
          if (targetNode.type === 'territory' && currentPlayer.activeCharacters.some(c => c.id === 'rahab')) points = 4;
          setChallengeProgress(prev => prev + points);
          showNotification(`Secured! +${points} PTS`, "emerald");
        }
    }

    setPlayers(updatedPlayers);
    setActionPoints(prev => prev - cost);
    setHasMoved(true);
  };

  const handleDrawCard = () => {
    if (actionPoints > 0 && supplyDeck.length > 0) {
      const currentSupply = [...supplyDeck];
      const card = currentSupply.shift();
      const updatedPlayers = [...players];
      
      if (card.type === 'Obligation') {
         if (mapNodes.some(n => n.id === card.targetNode)) {
           updatedPlayers[turnIndex].nodeId = card.targetNode;
           showNotification(card.desc, "red");
         } else {
           showNotification("Obligation ignored (Safe)", "zinc");
         }
         setSupplyDeck(currentSupply);
         setPlayers(updatedPlayers);
         setActionPoints(0); 
         return;
      }
      
      if (card.type === 'Trial') {
         updatedPlayers[turnIndex].activeCards.push(card);
         showNotification("Drawn Trial!", "red");
      } else {
         updatedPlayers[turnIndex].hand.push(card);
         showNotification("Drew 1 Card", "zinc");
      }
      
      setSupplyDeck(currentSupply);
      setPlayers(updatedPlayers);
      setActionPoints(prev => prev - 1);
    }
  };

  const handleInspectCard = (card) => { setInspectingCard(card); };

  const handlePlayCard = (card) => {
    setInspectingCard(null); 
    if (card.type === 'FaithAction') { setSelectedCard(card); setShowTrivia(true); }
    else if (card.type === 'Prayer') { 
      const abrahamBonus = players[turnIndex].activeCharacters.some(c => c.id === 'abraham') ? 1 : 0;
      playCardEffect(card, abrahamBonus); 
    }
    else if (card.type === 'Quality' || card.type === 'Trial') { activateCard(card); }
    else if (card.type === 'Character') { playCharacterCard(card); }
    else if (card.type === 'Action') { handleRemovalAction(card); }
  };
  
  const handleRemovalAction = (card) => {
    if (actionPoints <= 0) { showNotification("Not enough AP!", "yellow"); return; }
    const updatedPlayers = [...players];
    const currentPlayer = updatedPlayers[turnIndex];
    
    if (card.removeTarget === 'self') {
       if (currentPlayer.activeCards.length > 0) {
         currentPlayer.activeCards.shift(); 
         showNotification("Reflected. Trial Removed.", "blue");
       } else {
         showNotification("No trials to remove.", "zinc");
         return; 
       }
    } else if (card.removeTarget === 'other') {
       let range = 1;
       if (currentPlayer.activeCharacters.some(c => c.id === 'ruth')) range = 3;
       
       const target = updatedPlayers.find(p => p.id !== currentPlayer.id && p.activeCards.length > 0 && getDistance(currentPlayer.nodeId, p.nodeId, mapConnections) <= range);
       
       if (target) {
         target.activeCards.shift();
         showNotification(`Encouraged ${target.name}! Trial Removed.`, "blue");
       } else {
         showNotification("No one nearby needs help.", "zinc");
         return;
       }
    }
    
    currentPlayer.hand = currentPlayer.hand.filter(c => c.uniqueId !== card.uniqueId);
    setPlayers(updatedPlayers);
    setActionPoints(prev => prev - 1);
  };

  const playCharacterCard = (card) => {
    if (actionPoints <= 0) { showNotification("Not enough AP!", "yellow"); return; }
    const updatedPlayers = [...players];
    const player = updatedPlayers[turnIndex];
    
    if (player.activeCharacters.length < maxCharacters) {
      player.activeCharacters.push(card);
    } else {
      player.activeCharacters[0] = card;
    }
    
    player.hand = player.hand.filter(c => c.uniqueId !== card.uniqueId);
    setActionPoints(3); 
    showNotification("Fresh Zeal! AP Restored!", "amber");
    setPlayers(updatedPlayers);
  };

  const activateCard = (card) => {
    if (actionPoints <= 0) { showNotification("Not enough AP!", "yellow"); return; }
    const updatedPlayers = [...players];
    const player = updatedPlayers[turnIndex];
    player.hand = player.hand.filter(c => c.uniqueId !== card.uniqueId);
    player.activeCards.push(card);
    setPlayers(updatedPlayers);
    setActionPoints(prev => prev - 1);
    showNotification(`${card.type} Activated!`, "blue");
  };

  const handleTriviaResult = (success) => {
    setShowTrivia(false);
    const bonus = success ? selectedCard.bonus : 0;
    const davidBonus = players[turnIndex].activeCharacters.some(c => c.id === 'david') ? 1 : 0;
    playCardEffect(selectedCard, bonus + davidBonus);
    setSelectedCard(null);
  };

  const playCardEffect = (card, bonusPoints) => {
    if (actionPoints <= 0) { showNotification("Not enough AP!", "yellow"); return; }
    const points = (card.points || 0) + bonusPoints;
    if (currentChallenge) {
      setChallengeProgress(prev => prev + points);
      showNotification(`+${points} Points!`, "emerald");
    }
    const updatedPlayers = [...players];
    updatedPlayers[turnIndex].hand = updatedPlayers[turnIndex].hand.filter(c => c.uniqueId !== card.uniqueId);
    setPlayers(updatedPlayers);
    setActionPoints(prev => prev - 1);
  };

  const endTurn = () => {
    setOpenHandIndex(null);
    let currentSupply = [...supplyDeck];
    const updatedPlayers = [...players];
    const currentPlayerObj = updatedPlayers[turnIndex];

    const card1 = currentSupply.shift(); 
    if (card1) {
      if (card1.type === 'Obligation') {
          if (mapNodes.some(n => n.id === card1.targetNode)) {
             currentPlayerObj.nodeId = card1.targetNode;
             showNotification("Obligation! Teleported.", "red");
          }
      } else if (card1.type === 'Trial') {
          currentPlayerObj.activeCards.push(card1);
      } else {
          currentPlayerObj.hand.push(card1);
      }
    }
    
    if (currentPlayerObj.activeCharacters.some(c => c.id === 'esther')) {
       const card2 = currentSupply.shift(); 
       if(card2) {
         if (card2.type === 'Trial') currentPlayerObj.activeCards.push(card2);
         else currentPlayerObj.hand.push(card2);
         showNotification("Esther Bonus Draw!", "purple");
       }
    }

    setSupplyDeck(currentSupply);
    setPlayers(updatedPlayers);
    
    if (turnIndex === players.length - 1) endRound();
    else {
      setTurnIndex(prev => prev + 1);
      setActionPoints(3);
      setHasMoved(false);
    }
  };

  const endRound = () => {
    setRoundPhase('END');
    const success = challengeProgress >= (currentChallenge?.req || 0);
    if (success) {
      showNotification("Overcome!", "emerald");
      setUnity(u => Math.min(5, u + 1));
      setTrialDeck(prev => prev.slice(1));
      setCircumstanceDeck(prev => prev.slice(1));
    } else {
      showNotification("Failed!", "red");
      setUnity(u => Math.max(0, u - 1));
      setTrialDeck(prev => prev.slice(1));
      setCircumstanceDeck(prev => prev.slice(1));
    }
    setChallengeProgress(0);
    setCurrentChallenge(null);
    setCurrentCircumstance(null);
    setTimeout(() => { if(trialDeck.length > 1) startRound(); }, 2000); 
  };

  const showNotification = (msg, color) => {
    setNotification({ msg, color });
    setTimeout(() => setNotification(null), 2000);
  };

  const defaultPlayer = { id: -1, name: "Loading", color: "gray", activeCharacters: [], hand: [], activeCards: [], visitedSpecials: [], nodeId: "start_0", vacationPenalty: false };
  const currentPlayer = (players && players[turnIndex]) ? players[turnIndex] : defaultPlayer;

  const validMoves = useMemo(() => {
    if (gameState !== 'playing' || actionPoints <= 0 || !players.length) return [];
    const current = NODES.find(n => n.id === currentPlayer.nodeId);
    if (!current) return [];
    
    return CONNECTIONS
      .filter(c => c.start === current.id || c.end === current.id)
      .map(c => c.start === current.id ? c.end : c.start)
      .filter(targetId => {
         const targetNode = NODES.find(n => n.id === targetId);
         return targetNode.zone >= current.zone;
      });
  }, [currentPlayer, actionPoints, gameState, mapNodes]); 

  const tableRotation = -turnIndex * 90;
  
  const isCardPlayable = inspectingCard && currentPlayer.hand.some(c => c.uniqueId === inspectingCard.uniqueId);

  // --- RENDER ---

  if (gameState === 'setup') {
    return (
      <div className="min-h-screen bg-zinc-950 flex items-center justify-center p-4 text-white">
        <div className="max-w-md w-full text-center space-y-6">
          <Shield size={64} className="mx-auto text-amber-500 mb-4" />
          <h1 className="text-4xl font-black uppercase tracking-tighter">Covenant<br/>Tactical</h1>
          <p className="text-zinc-400">Cooperative Tabletop Mode</p>
          <div className="flex gap-4 justify-center">
            <button onClick={() => startGame(4)} className="w-16 h-16 bg-zinc-800 hover:bg-zinc-700 rounded-xl font-bold text-xl border border-zinc-700">Start 4P</button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="relative w-screen h-screen bg-zinc-950 overflow-hidden select-none font-sans text-zinc-100 flex items-center justify-center">
      
      {/* TABS */}
      <div className="absolute top-0 left-0 right-0 z-[100] flex justify-center bg-black/80 backdrop-blur border-b border-zinc-800 p-2">
         <div className="bg-zinc-800 rounded-full p-1 flex gap-1">
            <button onClick={() => setActiveTab('game')} className={`flex items-center gap-2 px-6 py-2 rounded-full text-xs font-bold uppercase ${activeTab === 'game' ? 'bg-amber-500 text-zinc-900' : 'text-zinc-400 hover:text-white'}`}><Gamepad2 size={14} /> Game</button>
            <button onClick={() => setActiveTab('manual')} className={`flex items-center gap-2 px-6 py-2 rounded-full text-xs font-bold uppercase ${activeTab === 'manual' ? 'bg-indigo-600 text-white' : 'text-zinc-400 hover:text-white'}`}><Book size={14} /> Rules</button>
         </div>
      </div>

      {activeTab === 'manual' && <div className="absolute inset-0 z-50 bg-zinc-950"><ManualView /></div>}

      <div className={`${activeTab === 'game' ? 'block' : 'hidden'} w-full h-full`}>
        
        {/* PHASE INDICATOR (TOP CENTER) */}
        {roundPhase === 'END' && (
          <div className="absolute top-20 left-1/2 -translate-x-1/2 z-50 animate-pulse">
            <span className="bg-emerald-600 text-white px-4 py-1 rounded-full text-xs font-bold uppercase tracking-widest border border-emerald-400 shadow-[0_0_20px_rgba(16,185,129,0.5)]">
              RESOLVING ROUND...
            </span>
          </div>
        )}

        {/* DECKS (TOP LEFT) */}
        <div className="absolute top-16 left-8 flex flex-col gap-4 z-40 pointer-events-auto">
           <div className="flex gap-4">
              <div className="relative group" onClick={() => handleInspectCard('trial_back')}>
                 <div className="absolute -top-3 left-0 text-[10px] font-bold text-red-500 bg-black/50 px-2 rounded">TRIAL</div>
                 <Card data="trial_back" isFaceUp={false} size="lg" onClick={()=>{}} />
                 <div className="absolute -bottom-2 -right-2 bg-red-600 text-[10px] font-bold w-6 h-6 rounded-full flex items-center justify-center text-white border-2 border-zinc-900">{trialDeck.length}</div>
              </div>
              <div className="relative group" onClick={() => handleInspectCard('circumstance_back')}>
                 <div className="absolute -top-3 left-0 text-[10px] font-bold text-slate-400 bg-black/50 px-2 rounded">COND.</div>
                 <Card data="circumstance_back" isFaceUp={false} size="lg" onClick={()=>{}} />
                 <div className="absolute -bottom-2 -right-2 bg-slate-500 text-[10px] font-bold w-6 h-6 rounded-full flex items-center justify-center text-white border-2 border-zinc-900">{circumstanceDeck.length}</div>
              </div>
              <div className="relative group cursor-pointer active:scale-95 transition-transform" onClick={handleDrawCard}>
                 <div className="absolute -top-3 left-0 text-[10px] font-bold text-indigo-400 bg-black/50 px-2 rounded">PROVISIONS</div>
                 <Card data="supply_back" isFaceUp={false} size="lg" onClick={()=>{}} />
                 <div className="absolute -bottom-2 -right-2 bg-indigo-600 text-[10px] font-bold w-6 h-6 rounded-full flex items-center justify-center text-white border-2 border-zinc-900">{supplyDeck.length}</div>
                 <div className="absolute inset-0 flex items-center justify-center opacity-0 group-hover:opacity-100 bg-black/50 rounded text-[10px] font-bold text-white transition-opacity text-center">DRAW<br/>1 AP</div>
              </div>
           </div>
           <div className="flex gap-4 mt-2">
              {currentChallenge ? <div className="relative animate-in slide-in-from-top-4" onClick={() => handleInspectCard(currentChallenge)}><div className="absolute -top-3 left-0 text-[10px] font-bold text-red-500 bg-black/50 px-2 rounded flex items-center gap-1"><AlertTriangle size={8} /> THREAT</div><Card data={currentChallenge} isFaceUp={true} size="lg" onClick={()=>{}} /></div> : <div className="w-24 h-40 border border-zinc-700/50 rounded flex items-center justify-center text-[10px] text-zinc-600">SAFE</div>}
              {currentCircumstance ? <div className="relative animate-in slide-in-from-top-4 delay-100" onClick={() => handleInspectCard(currentCircumstance)}><div className="absolute -top-3 left-0 text-[10px] font-bold text-slate-400 bg-black/50 px-2 rounded flex items-center gap-1"><Layers size={8} /> COND.</div><Card data={currentCircumstance} isFaceUp={true} size="lg" onClick={()=>{}} /></div> : <div className="w-24 h-40 border border-dashed border-zinc-700/50 rounded flex items-center justify-center text-[10px] text-zinc-600">NORMAL</div>}
           </div>
        </div>

        {/* HUD (TOP RIGHT) */}
        <div className="absolute top-16 right-8 z-40 pointer-events-auto flex flex-col items-end">
           {currentChallenge && (
              <div className="bg-black/60 backdrop-blur border border-zinc-700 p-4 rounded-xl text-right shadow-2xl animate-in slide-in-from-right">
                 <div className="text-[10px] text-zinc-400 font-bold uppercase tracking-widest mb-1 flex items-center justify-end gap-2"><CloudLightning size={12} className="text-amber-500" /> Faith Required</div>
                 <div className="text-3xl font-black text-white tabular-nums">{challengeProgress} <span className="text-zinc-500 text-lg">/ {currentChallenge.req}</span></div>
                 <div className="w-48 h-2 bg-zinc-800 rounded-full mt-2 overflow-hidden"><div className="h-full bg-gradient-to-r from-red-600 via-amber-500 to-emerald-500 transition-all duration-700" style={{ width: `${Math.min(100, (challengeProgress / currentChallenge.req) * 100)}%` }} /></div>
              </div>
           )}
           <div className="mt-4 flex flex-col items-end">
               <div className="text-[8px] font-bold text-zinc-500 uppercase tracking-widest mb-1">Unity</div>
               <div className="flex gap-1.5 p-2 bg-zinc-900/80 rounded-lg border border-zinc-800">
                 {[1,2,3,4,5].map(i => <div key={i} className={`w-1.5 h-4 rounded-full transition-all ${i <= unity ? 'bg-emerald-500 shadow-[0_0_8px_rgba(16,185,129,0.6)]' : 'bg-zinc-800'}`} />)}
               </div>
           </div>
        </div>

        {/* PLAYER STATUS & ACTIVE CARDS (BOTTOM LEFT) */}
        <div className="absolute bottom-8 left-8 z-40 flex flex-col gap-4 pointer-events-auto">
           {/* Active Characters */}
           <div className="flex flex-col gap-2">
             <div className="text-[10px] font-bold text-zinc-500 uppercase tracking-widest">Active Characters</div>
             <div className="flex gap-2">
               {currentPlayer.activeCharacters.map((char, i) => (
                 <div key={i} className="bg-zinc-900 border border-zinc-700 rounded-xl p-3 flex items-center gap-3 shadow-lg min-w-[220px]">
                    <div className="bg-amber-600/20 text-amber-500 p-2 rounded-full">{char.icon || <UserPlus size={16} />}</div>
                    <div>
                      <div className="text-sm font-black text-white">{char.name}</div>
                      <div className="text-[10px] font-bold text-amber-500 uppercase tracking-wider">{char.ability}</div>
                      <div className="text-[9px] text-zinc-300 leading-tight mt-1">{char.desc}</div>
                    </div>
                 </div>
               ))}
             </div>
           </div>

           {/* Active Cards (Tableau) */}
           <div className="flex gap-2 p-2 bg-black/40 rounded-xl backdrop-blur-sm border border-white/5 max-w-[400px] overflow-x-auto min-h-[100px] items-center">
              {currentPlayer.activeCards.length > 0 ? currentPlayer.activeCards.map(c => (
                 <Card key={c.uniqueId} data={c} size="sm" isFaceUp={true} isSelected={false} onClick={() => handleInspectCard(c)} />
              )) : (
                 <div className="text-xs text-zinc-600 font-bold p-4 uppercase tracking-widest w-full text-center">No Active Effects</div>
              )}
           </div>

           {/* Player Pill */}
           <div className="bg-zinc-900 border border-zinc-700 rounded-2xl p-4 flex items-center gap-4 shadow-2xl">
              <div className="w-12 h-12 rounded-full border-4 flex items-center justify-center text-xl font-bold shadow-lg" style={{ borderColor: currentPlayer.color, backgroundColor: currentPlayer.color }}>{currentPlayer.activeCharacters[0]?.name.charAt(0)}</div>
              <div>
                 <div className="text-xs font-bold text-zinc-400 uppercase tracking-widest">Active Player</div>
                 <div className="text-xl font-black text-white">{currentPlayer.activeCharacters.map(c => c.name).join(' & ')}</div>
              </div>
              <div className="h-10 w-px bg-zinc-700 mx-2"></div>
              <div className="text-center">
                 <div className="text-xs font-bold text-zinc-400 uppercase">Actions</div>
                 <div className="text-2xl font-black text-amber-500">{actionPoints}</div>
              </div>
           </div>
        </div>

        {/* ROTATING TABLE (CENTER) */}
        <div className="relative w-[100vmin] h-[100vmin] transition-transform duration-1000 ease-in-out mx-auto mt-12" style={{ transform: `rotate(${tableRotation}deg)` }}>
          <div className="absolute inset-0 m-auto w-[80vmin] h-[80vmin] rounded-full bg-zinc-900/50 border-4 border-zinc-800 shadow-2xl overflow-hidden backdrop-blur-sm" onClick={() => setOpenHandIndex(null)}>
            <NodeMap players={players} nodes={mapNodes} connections={mapConnections} activePlayerId={currentPlayer.id} validMoves={validMoves} onNodeClick={handleNodeInteraction} />
          </div>
          {players.map((p, i) => (
            <PlayerHand key={p.id} player={p} isActive={turnIndex === i} rotation={i} isOpen={openHandIndex === i} toggleHand={(e) => { e.stopPropagation(); setOpenHandIndex(openHandIndex === i ? null : i); }} onCardClick={(c) => handleInspectCard(c)} />
          ))}
        </div>

        {/* End Turn Button (BOTTOM RIGHT) */}
        <div className="absolute bottom-8 right-8 z-50">
          <button onClick={endTurn} className="bg-amber-500 hover:bg-amber-400 text-zinc-900 font-black uppercase px-8 py-4 rounded-2xl shadow-xl shadow-amber-500/20 active:scale-95 transition-all flex flex-col items-center">
            <span>End Turn</span><span className="text-[10px] opacity-70 font-normal">Pass to Next</span>
          </button>
        </div>

        {/* MODALS */}
        {inspectingCard && typeof inspectingCard === 'object' && <CardInspectionModal card={inspectingCard} onClose={() => setInspectingCard(null)} onPlay={() => handlePlayCard(inspectingCard)} canPlay={isCardPlayable} isPlayerTurn={true} />}
        {inspectingNode && <NodeInspectionModal node={inspectingNode} onClose={() => setInspectingNode(null)} onTravel={() => executeMove(inspectingNode.id, inspectingNode.travelCost)} canTravel={inspectingNode.canTravel} travelCost={inspectingNode.travelCost} />}
        {showTrivia && selectedCard && <TriviaModal card={selectedCard} onResult={handleTriviaResult} />}
        
        {notification && <div className="absolute top-32 left-1/2 -translate-x-1/2 z-50 animate-in fade-in zoom-in duration-300 pointer-events-none"><div className={`px-6 py-3 rounded-full font-black text-sm uppercase tracking-widest shadow-2xl border-2 flex items-center gap-2 ${notification.color === 'red' ? 'bg-red-900 border-red-500 text-white' : 'bg-zinc-800 border-zinc-600 text-white'}`}>{notification.msg}</div></div>}
      </div>
    </div>
  );
}