import React from 'react';
import { 
  Shield, Eye, Shuffle, SkipForward, Gift, 
  HeartHandshake, Grape, Heart, AlertTriangle,
  Sword, HardHat, Footprints, Shirt, Octagon, Users, 
  Spline, Clock, Gem, CloudRain, Scissors, Copy, User,
  Brain, Star, Wrench, Search, HandHeart, RotateCcw, Filter
} from 'lucide-react';
import { CHARACTERS_DB } from './characters';

export const CARD_TYPES = {
  // HAZARDS
  stumble: { id: 'stumble', title: 'The Stumble', desc: 'Unity -1 (Reduces Help Range).', scripture: { text: 'For the righteous one may fall seven times, and he will get up again, but the wicked will be made to stumble by calamity.', ref: 'Pr 24:16' }, color: 'bg-gradient-to-br from-red-600 via-red-700 to-red-800 border-2 border-red-400 shadow-[0_0_20px_rgba(220,38,38,0.4)]', textColor: 'text-white', icon: AlertTriangle },
  discord: { id: 'discord', title: 'Discord', desc: 'Unity -1 (Reduces Help Range).', scripture: { text: 'I urge you, brothers, through the name of our Lord Jesus Christ, that you should all speak in agreement and that there should be no divisions among you.', ref: '1Co 1:10' }, color: 'bg-gradient-to-br from-orange-700 via-orange-800 to-orange-900 border-2 border-orange-500 shadow-[0_0_20px_rgba(194,65,12,0.4)]', textColor: 'text-white', icon: Spline },
  
  // ACTIONS - All use same dark navy/gray base color with different accent colors
  faith: { id: 'faith', title: 'Faith', desc: 'Defuse a Stumble.', scripture: { text: 'Faith is the assured expectation of what is hoped for, the evident demonstration of realities that are not seen.', ref: 'Heb 11:1' }, color: 'bg-gradient-to-br from-slate-800 via-slate-900 to-slate-950 border-2 border-emerald-400 shadow-[0_0_20px_rgba(52,211,153,0.3)]', textColor: 'text-emerald-400', icon: Shield },
  encouragement: { id: 'encouragement', title: 'Encouragement', desc: 'Save friend OR Remove Burden.', scripture: { text: 'Keep encouraging one another and building one another up.', ref: '1Th 5:11' }, color: 'bg-gradient-to-br from-slate-800 via-slate-900 to-slate-950 border-2 border-amber-400 shadow-[0_0_20px_rgba(251,191,36,0.3)]', textColor: 'text-amber-400', icon: HeartHandshake },
  insight: { id: 'insight', title: 'Insight', desc: 'See top cards (Unity Level).', scripture: { text: 'If you call out for understanding and raise your voice for insight, you will find the knowledge of God.', ref: 'Pr 2:3, 4' }, color: 'bg-gradient-to-br from-slate-800 via-slate-900 to-slate-950 border-2 border-indigo-400 shadow-[0_0_20px_rgba(129,140,248,0.3)]', textColor: 'text-indigo-400', icon: Eye },
  guidance: { id: 'guidance', title: 'Guidance', desc: 'Request a card from a player within range.', scripture: { text: 'Trust in Jehovah with all your heart, and do not rely on your own understanding. In all your ways take notice of him, and he will make your paths straight.', ref: 'Pr 3:5, 6' }, color: 'bg-gradient-to-br from-slate-800 via-slate-900 to-slate-950 border-2 border-purple-400 shadow-[0_0_20px_rgba(192,132,252,0.3)]', textColor: 'text-purple-400', icon: HandHeart },
  patience: { id: 'patience', title: 'Patience', desc: 'Move top card down (Unity Level spots).', scripture: { text: 'Rejoice in the hope. Endure under tribulation. Persevere in prayer.', ref: 'Ro 12:12' }, color: 'bg-gradient-to-br from-slate-800 via-slate-900 to-slate-950 border-2 border-blue-400 shadow-[0_0_20px_rgba(96,165,250,0.3)]', textColor: 'text-blue-400', icon: SkipForward },
  modesty: { id: 'modesty', title: 'Modesty', desc: 'Skip Turn. Next player draws 2.', scripture: { text: 'Let the women adorn themselves in well-arranged dress, with modesty and soundness of mind.', ref: '1Ti 2:9' }, color: 'bg-gradient-to-br from-slate-800 via-slate-900 to-slate-950 border-2 border-cyan-400 shadow-[0_0_20px_rgba(34,211,238,0.3)]', textColor: 'text-cyan-400', icon: User },
  kindness: { id: 'kindness', title: 'Kindness', desc: 'Give a card to a friend.', scripture: { text: 'Become kind to one another, tenderly compassionate, freely forgiving one another.', ref: 'Eph 4:32' }, color: 'bg-gradient-to-br from-slate-800 via-slate-900 to-slate-950 border-2 border-pink-400 shadow-[0_0_20px_rgba(244,114,182,0.3)]', textColor: 'text-pink-400', icon: Gift },
  imitate: { id: 'imitate', title: 'Imitate Faith', desc: 'Copy a buff from another player (1 Turn).', scripture: { text: 'Remember those who are taking the lead among you, who have spoken the word of God to you, and as you contemplate how their conduct turns out, imitate their faith.', ref: 'Heb 13:7' }, color: 'bg-gradient-to-br from-slate-800 via-slate-900 to-slate-950 border-2 border-teal-400 shadow-[0_0_20px_rgba(45,212,191,0.3)]', textColor: 'text-teal-400', icon: Copy },
  wisdom: { id: 'wisdom', title: 'Wisdom', desc: 'Look at top cards (Unity Level), rearrange same number.', scripture: { text: 'Wisdom is the most important thing, so acquire wisdom, and with all you acquire, acquire understanding.', ref: 'Pr 4:7' }, color: 'bg-gradient-to-br from-slate-800 via-slate-900 to-slate-950 border-2 border-violet-400 shadow-[0_0_20px_rgba(167,139,250,0.3)]', textColor: 'text-violet-400', icon: Brain },
  prayer: { id: 'prayer', title: 'Prayer', desc: 'Draw 1. If Fruit/Love, keep. Else shuffle back.', scripture: { text: 'Do not be anxious over anything, but in everything by prayer and supplication along with thanksgiving, let your petitions be made known to God.', ref: 'Php 4:6' }, color: 'bg-gradient-to-br from-slate-800 via-slate-900 to-slate-950 border-2 border-yellow-400 shadow-[0_0_20px_rgba(250,204,21,0.3)]', textColor: 'text-yellow-400', icon: Star },
  minister: { id: 'minister', title: 'Minister', desc: 'Remove 1 burden OR give 1 card.', scripture: { text: 'He has indeed adequately qualified us to be ministers of a new covenant.', ref: '2Co 3:6' }, color: 'bg-gradient-to-br from-slate-800 via-slate-900 to-slate-950 border-2 border-amber-500 shadow-[0_0_20px_rgba(245,158,11,0.3)]', textColor: 'text-amber-500', icon: Wrench },
  vigilance: { id: 'vigilance', title: 'Vigilance', desc: 'Look at top cards (Unity Level), discard 1 burden.', scripture: { text: 'Keep your senses, be watchful. Your adversary, the Devil, walks about like a roaring lion, seeking to devour someone.', ref: '1Pe 5:8' }, color: 'bg-gradient-to-br from-slate-800 via-slate-900 to-slate-950 border-2 border-purple-500 shadow-[0_0_20px_rgba(168,85,247,0.3)]', textColor: 'text-purple-500', icon: Search },
  discernment: { id: 'discernment', title: 'Discernment', desc: 'Discard the next card drawn (except Stumble).', scripture: { text: 'Solid food belongs to mature people, to those who through use have their powers of discernment trained to distinguish both right and wrong.', ref: 'Heb 5:14' }, color: 'bg-gradient-to-br from-slate-800 via-slate-900 to-slate-950 border-2 border-cyan-400 shadow-[0_0_20px_rgba(34,211,238,0.3)]', textColor: 'text-cyan-400', icon: Filter },
  resurrection: { id: 'resurrection', title: 'Resurrection', desc: 'Revive a knocked out player.', scripture: { text: 'For the Lord himself will descend from heaven with a commanding call, with an archangel\'s voice and with God\'s trumpet, and those who are dead in union with Christ will rise first.', ref: '1Th 4:16' }, color: 'bg-gradient-to-br from-slate-800 via-slate-900 to-slate-950 border-2 border-rose-400 shadow-[0_0_20px_rgba(251,113,133,0.3)]', textColor: 'text-rose-400', icon: RotateCcw },
  days_cut_short: { id: 'days_cut_short', title: 'Days Cut Short', desc: 'Divine Intervention: End Great Tribulation.', scripture: { text: 'In fact, unless those days were cut short, no one would be saved; but on account of the chosen ones those days will be cut short.', ref: 'Mt 24:22' }, color: 'bg-gradient-to-br from-slate-100 via-amber-50 to-amber-100 border-2 border-amber-400 shadow-[0_0_20px_rgba(251,191,36,0.4)]', textColor: 'text-black', icon: Scissors },
  
  // COLLECTION
  fruit: { id: 'fruit', title: 'Fruitage', desc: 'Action: Play to Heal 1 Unity.', scripture: { text: 'The fruitage of the spirit is love, joy, peace, patience, kindness, goodness, faith, mildness, self-control.', ref: 'Ga 5:22, 23' }, color: 'bg-gradient-to-br from-lime-500 via-emerald-500 to-green-600 border-2 border-lime-300 shadow-[0_0_20px_rgba(132,204,22,0.4)]', textColor: 'text-white', icon: Grape },
  love: { id: 'love', title: 'Love Is...', desc: 'Action: Play to Heal 1 Unity.', scripture: { text: 'Love is patient and kind. Love is not jealous. It does not brag, does not get puffed up, does not behave indecently, does not look for its own interests, does not become provoked. It does not keep account of the injury.', ref: '1Co 13:4, 5' }, color: 'bg-gradient-to-br from-pink-500 via-rose-500 to-red-600 border-2 border-pink-300 shadow-[0_0_20px_rgba(236,72,153,0.4)]', textColor: 'text-white', icon: Heart },
  
  // PERSONAL TRIALS
  trial_anxiety: { id: 'trial_anxiety', title: 'Anxiety', desc: 'Burden: Discards 1 Active Card.', scripture: { text: 'Do not be anxious over anything, but in everything by prayer and supplication along with thanksgiving, let your petitions be made known to God; and the peace of God will guard your hearts.', ref: 'Php 4:6, 7' }, color: 'bg-gradient-to-br from-zinc-700 via-zinc-800 to-zinc-900 border-2 border-red-500 shadow-[0_0_20px_rgba(239,68,68,0.4)]', textColor: 'text-white', icon: AlertTriangle },
  trial_time: { id: 'trial_time', title: 'Unwise Time', desc: 'Burden: Skip Next Turn.', scripture: { text: 'Keep strict watch that how you walk is not as unwise but as wise persons, making the best use of your time.', ref: 'Eph 5:15, 16' }, color: 'bg-gradient-to-br from-zinc-700 via-zinc-800 to-zinc-900 border-2 border-red-500 shadow-[0_0_20px_rgba(239,68,68,0.4)]', textColor: 'text-white', icon: Clock },
  trial_materialism: { id: 'trial_materialism', title: 'Materialism', desc: 'Burden: Lose 1 Fruit to Deck.', scripture: { text: 'The love of money is a root of all sorts of injurious things.', ref: '1Ti 6:10' }, color: 'bg-gradient-to-br from-zinc-700 via-zinc-800 to-zinc-900 border-2 border-red-500 shadow-[0_0_20px_rgba(239,68,68,0.4)]', textColor: 'text-white', icon: Gem },
  trial_doubt: { id: 'trial_doubt', title: 'Doubt', desc: 'Burden: Cannot play Faith/Encourage.', scripture: { text: 'But let him keep asking in faith, not doubting at all, for the one who doubts is like a wave of the sea driven by the wind and blown about.', ref: 'Jas 1:6' }, color: 'bg-gradient-to-br from-zinc-700 via-zinc-800 to-zinc-900 border-2 border-red-500 shadow-[0_0_20px_rgba(239,68,68,0.4)]', textColor: 'text-white', icon: CloudRain },
  trial_associations: { id: 'trial_associations', title: 'Bad Company', desc: 'Burden: Cannot Receive Help.', scripture: { text: 'Do not be misled. Bad associations spoil useful habits.', ref: '1Co 15:33' }, color: 'bg-gradient-to-br from-zinc-700 via-zinc-800 to-zinc-900 border-2 border-red-500 shadow-[0_0_20px_rgba(239,68,68,0.4)]', textColor: 'text-white', icon: Users },

  // ARMOR
  belt: { id: 'belt', title: 'Belt of Truth', desc: 'Active: Insight reveals Unity Level +2.', scripture: { text: 'Stand firm, therefore, with the belt of truth fastened around your waist.', ref: 'Eph 6:14' }, color: 'bg-gradient-to-br from-amber-800 via-amber-900 to-amber-950 border-2 border-amber-700 shadow-[0_0_20px_rgba(180,83,9,0.4)]', textColor: 'text-white', icon: Octagon },
  breastplate: { id: 'breastplate', title: 'Breastplate', desc: 'Active: Fruit heals Unity.', scripture: { text: 'Wearing the breastplate of righteousness.', ref: 'Eph 6:14' }, color: 'bg-gradient-to-br from-amber-800 via-amber-900 to-amber-950 border-2 border-amber-700 shadow-[0_0_20px_rgba(180,83,9,0.4)]', textColor: 'text-white', icon: Shirt },
  sandals: { id: 'sandals', title: 'Sandals', desc: 'Active: Patience pushes Unity Level +2 deep.', scripture: { text: 'With your feet shod in readiness to declare the good news of peace.', ref: 'Eph 6:15' }, color: 'bg-gradient-to-br from-amber-800 via-amber-900 to-amber-950 border-2 border-amber-700 shadow-[0_0_20px_rgba(180,83,9,0.4)]', textColor: 'text-white', icon: Footprints },
  shield_equip: { id: 'shield_equip', title: 'Large Shield', desc: 'Active: Auto-Defuse 1.', scripture: { text: 'Take up the large shield of faith, with which you will be able to extinguish all the wicked one\'s burning arrows.', ref: 'Eph 6:16' }, color: 'bg-gradient-to-br from-amber-800 via-amber-900 to-amber-950 border-2 border-amber-700 shadow-[0_0_20px_rgba(180,83,9,0.4)]', textColor: 'text-white', icon: Shield },
  helmet: { id: 'helmet', title: 'Helmet', desc: 'Active: Prevent 1 Knockout.', scripture: { text: 'Accept the helmet of salvation.', ref: 'Eph 6:17' }, color: 'bg-gradient-to-br from-amber-800 via-amber-900 to-amber-950 border-2 border-amber-700 shadow-[0_0_20px_rgba(180,83,9,0.4)]', textColor: 'text-white', icon: HardHat },
  sword: { id: 'sword', title: 'Sword', desc: 'Active: Peek on Shuffle.', scripture: { text: 'The sword of the spirit, that is, God\'s word.', ref: 'Eph 6:17' }, color: 'bg-gradient-to-br from-amber-800 via-amber-900 to-amber-950 border-2 border-amber-700 shadow-[0_0_20px_rgba(180,83,9,0.4)]', textColor: 'text-white', icon: Sword },
};

// Add characters to CARD_TYPES
CHARACTERS_DB.forEach(char => {
    (CARD_TYPES as any)[char.id] = char;
});

// Export as any to avoid TypeScript issues with dynamic properties
export default CARD_TYPES as any;

export const FRUITS = ["Love", "Joy", "Peace", "Patience", "Kindness", "Goodness", "Faith", "Mildness", "Self-Control"];
export const LOVE_TRAITS = ["Patient", "Kind", "Not Jealous", "Not Bragging", "Not Puffed Up", "Decent", "Unselfish", "Not Provoked", "Forgiving"];

