import { Wind, Heart, Shield, Crown, Star, Lock, Anchor, Smile, Sun } from 'lucide-react';

export const CHARACTERS_DB = [
  { id: 'char_moses', title: 'Moses', desc: 'Active: Immune to "Unwise Time".', scripture: { text: 'Come, and I will send you to Pharaoh, and you will bring my people the Israelites out of Egypt.', ref: 'Ex 3:10' }, color: 'bg-gradient-to-br from-violet-600 via-violet-700 to-purple-800 border-2 border-violet-400 shadow-[0_0_20px_rgba(139,92,246,0.4)]', textColor: 'text-white', icon: Wind },
  { id: 'char_ruth', title: 'Ruth', desc: 'Active: Help Range is Infinite.', scripture: { text: 'Do not urge me to abandon you, to turn back from accompanying you. For wherever you go, I will go, and wherever you spend the night, I will spend the night. Your people will be my people, and your God my God.', ref: 'Ru 1:16' }, color: 'bg-gradient-to-br from-violet-600 via-violet-700 to-purple-800 border-2 border-violet-400 shadow-[0_0_20px_rgba(139,92,246,0.4)]', textColor: 'text-white', icon: Heart },
  { id: 'char_david', title: 'David', desc: 'Active: Immune to "Anxiety".', scripture: { text: 'Then Samuel took the horn of oil and anointed him in the midst of his brothers, and the spirit of Jehovah was at work upon David from that day forward.', ref: '1Sa 16:13' }, color: 'bg-gradient-to-br from-violet-600 via-violet-700 to-purple-800 border-2 border-violet-400 shadow-[0_0_20px_rgba(139,92,246,0.4)]', textColor: 'text-white', icon: Shield },
  { id: 'char_esther', title: 'Esther', desc: 'Active: Draw 1 extra card.', scripture: { text: 'Who knows whether it is for a time like this that you have attained to your royal position?', ref: 'Es 4:14' }, color: 'bg-gradient-to-br from-violet-600 via-violet-700 to-purple-800 border-2 border-violet-400 shadow-[0_0_20px_rgba(139,92,246,0.4)]', textColor: 'text-white', icon: Crown },
  { id: 'char_abraham', title: 'Abraham', desc: 'Active: Can use "Faith" on others.', scripture: { text: 'By faith Abraham, when he was called, obeyed by going out to a place he was to receive as an inheritance; and he went out, although not knowing where he was going.', ref: 'Heb 11:8' }, color: 'bg-gradient-to-br from-violet-600 via-violet-700 to-purple-800 border-2 border-violet-400 shadow-[0_0_20px_rgba(139,92,246,0.4)]', textColor: 'text-white', icon: Star },
  { id: 'char_daniel', title: 'Daniel', desc: 'Active: Immune to "Materialism".', scripture: { text: 'But Daniel resolved in his heart that he would not defile himself with the king\'s delicacies or with the wine he drank.', ref: 'Da 1:8' }, color: 'bg-gradient-to-br from-violet-600 via-violet-700 to-purple-800 border-2 border-violet-400 shadow-[0_0_20px_rgba(139,92,246,0.4)]', textColor: 'text-white', icon: Lock },
  { id: 'char_noah', title: 'Noah', desc: 'Active: Immune to "Bad Company".', scripture: { text: 'Noah was a righteous man. He proved himself faultless among his contemporaries. Noah walked with the true God.', ref: 'Ge 6:9' }, color: 'bg-gradient-to-br from-violet-600 via-violet-700 to-purple-800 border-2 border-violet-400 shadow-[0_0_20px_rgba(139,92,246,0.4)]', textColor: 'text-white', icon: Anchor },
  { id: 'char_sarah', title: 'Sarah', desc: 'Active: Immune to "Doubt" on draw. Removes ALL active Doubt cards when activated.', scripture: { text: 'By faith also Sarah herself received power to conceive seed, even when she was past the age limit, since she considered him faithful who had promised.', ref: 'Heb 11:11' }, color: 'bg-gradient-to-br from-violet-600 via-violet-700 to-purple-800 border-2 border-violet-400 shadow-[0_0_20px_rgba(139,92,246,0.4)]', textColor: 'text-white', icon: Smile },
  { id: 'char_job', title: 'Job', desc: 'Active: Can be helped by anyone.', scripture: { text: 'There was a man in the land of Uz whose name was Job, and that man was blameless and upright, and he feared God and shunned what was bad.', ref: 'Job 1:1' }, color: 'bg-gradient-to-br from-violet-600 via-violet-700 to-purple-800 border-2 border-violet-400 shadow-[0_0_20px_rgba(139,92,246,0.4)]', textColor: 'text-white', icon: Sun },
];

