export const TRIVIA_DB = {
  EASY: [
    { q: "Who built the Ark?", a: "Noah", options: ["Moses", "Noah", "David"], source: "https://wol.jw.org/en/wol/s/r1/lp-e?q=Noah%20built%20ark%20Genesis%206%3A14" },
    { q: "How many apostles did Jesus have?", a: "12", options: ["10", "12", "7"], source: "https://wol.jw.org/en/wol/s/r1/lp-e?q=twelve%20apostles%20Matthew%2010%3A2" },
    { q: "Where was Jesus born?", a: "Bethlehem", options: ["Nazareth", "Bethlehem", "Jerusalem"], source: "https://wol.jw.org/en/wol/s/r1/lp-e?q=Jesus%20born%20Bethlehem%20Matthew%202%3A1" },
    { q: "Who defeated Goliath?", a: "David", options: ["Saul", "Jonathan", "David"], source: "https://wol.jw.org/en/wol/s/r1/lp-e?q=David%20defeated%20Goliath%201%20Samuel%2017%3A50" },
    { q: "First book of the Bible?", a: "Genesis", options: ["Exodus", "Genesis", "Job"], source: "https://wol.jw.org/en/wol/s/r1/lp-e?q=Genesis%20first%20book%20Bible" },
    { q: "Who spoke to the burning bush?", a: "Moses", options: ["Moses", "Aaron", "Joshua"], source: "https://wol.jw.org/en/wol/s/r1/lp-e?q=Moses%20burning%20bush%20Exodus%203%3A2" },
    { q: "Which apostle walked on water briefly?", a: "Peter", options: ["Peter", "John", "James"], source: "https://wol.jw.org/en/wol/s/r1/lp-e?q=Peter%20walked%20on%20water%20Matthew%2014%3A29" },
    { q: "Who was the first king of Israel?", a: "Saul", options: ["Saul", "David", "Solomon"], source: "https://wol.jw.org/en/wol/s/r1/lp-e?q=Saul%20first%20king%20Israel%201%20Samuel%2010%3A1" },
    { q: "Which prophet was thrown into a lions' den?", a: "Daniel", options: ["Daniel", "Jeremiah", "Ezekiel"], source: "https://wol.jw.org/en/wol/s/r1/lp-e?q=Daniel%20lions%27%20den%20Daniel%206%3A16" },
    { q: "Who built an ark to save his family?", a: "Noah", options: ["Noah", "Moses", "Abraham"], source: "https://wol.jw.org/en/wol/s/r1/lp-e?q=Noah%20built%20ark%20save%20family%20Genesis%206%3A14" },
    { q: "Which prophet was swallowed by a great fish?", a: "Jonah", options: ["Jonah", "Ezekiel", "Isaiah"], source: "https://wol.jw.org/en/wol/s/r1/lp-e?q=Jonah%20swallowed%20great%20fish%20Jonah%201%3A17" },
    { q: "Who defeated Goliath with a sling?", a: "David", options: ["David", "Saul", "Jonathan"], source: "https://wol.jw.org/en/wol/s/r1/lp-e?q=David%20Goliath%20sling%201%20Samuel%2017%3A50" },
    { q: "Who was the father of many nations?", a: "Abraham", options: ["Abraham", "Isaac", "Jacob"], source: "https://wol.jw.org/en/wol/s/r1/lp-e?q=Abraham%20father%20many%20nations%20Genesis%2017%3A5" },
    { q: "Which woman helped hide the spies in Jericho?", a: "Rahab", options: ["Rahab", "Ruth", "Esther"], source: "https://wol.jw.org/en/wol/s/r1/lp-e?q=Rahab%20hid%20spies%20Jericho%20Joshua%202%3A1" },
    { q: "Who was called the \"Rock\" by Jesus?", a: "Peter", options: ["Peter", "John", "James"], source: "https://wol.jw.org/en/wol/s/r1/lp-e?q=Peter%20Rock%20Jesus%20Matthew%2016%3A18" },
    { q: "Which king was known as a man after God's own heart?", a: "David", options: ["David", "Saul", "Solomon"], source: "https://wol.jw.org/en/wol/s/r1/lp-e?q=David%20man%20after%20God%27s%20heart%201%20Samuel%2013%3A14" },
    { q: "Who wrote most of the Christian Greek Scriptures letters?", a: "Paul", options: ["Paul", "Peter", "John"], source: "https://wol.jw.org/en/wol/s/r1/lp-e?q=Paul%20wrote%20letters%20Christian%20Greek%20Scriptures" },
    { q: "Which woman showed loyalty to her mother-in-law?", a: "Ruth", options: ["Ruth", "Esther", "Mary"], source: "https://wol.jw.org/en/wol/s/r1/lp-e?q=Ruth%20loyalty%20mother-in-law%20Ruth%201%3A16" },
    { q: "Who was the queen who saved her people?", a: "Esther", options: ["Esther", "Ruth", "Mary"], source: "https://wol.jw.org/en/wol/s/r1/lp-e?q=Esther%20queen%20saved%20people%20Esther%207%3A3" },
    { q: "Who was known as the \"Apostle to the Gentiles\"?", a: "Paul", options: ["Paul", "Peter", "James"], source: "https://wol.jw.org/en/wol/s/r1/lp-e?q=Paul%20Apostle%20Gentiles%20Acts%209%3A15" },
    { q: "In which city was Jesus born?", a: "Bethlehem", options: ["Bethlehem", "Nazareth", "Jerusalem"], source: "https://wol.jw.org/en/wol/s/r1/lp-e?q=Jesus%20born%20Bethlehem%20Matthew%202%3A1" },
    { q: "What was the name of the garden where Adam and Eve lived?", a: "Eden", options: ["Eden", "Gethsemane", "Paradise"], source: "https://wol.jw.org/en/wol/s/r1/lp-e?q=garden%20of%20Eden%20Adam%20Eve%20Genesis%202%3A8" },
    { q: "How many days was Jesus in the tomb?", a: "Three", options: ["Three", "Two", "Four"], source: "https://wol.jw.org/en/wol/s/r1/lp-e?q=Jesus%20tomb%20three%20days%20Matthew%2012%3A40" },
    { q: "What was the name of the sea that Moses parted?", a: "Red Sea", options: ["Red Sea", "Dead Sea", "Mediterranean"], source: "https://wol.jw.org/en/wol/s/r1/lp-e?q=Moses%20parted%20Red%20Sea%20Exodus%2014%3A21" },
    { q: "Who was the first man created by God?", a: "Adam", options: ["Adam", "Noah", "Abraham"], source: "https://wol.jw.org/en/wol/s/r1/lp-e?q=Adam%20first%20man%20created%20Genesis%201%3A27" },
    { q: "What was the name of Jesus' mother?", a: "Mary", options: ["Mary", "Elizabeth", "Sarah"], source: "https://wol.jw.org/en/wol/s/r1/lp-e?q=Mary%20mother%20Jesus%20Matthew%201%3A16" },
    { q: "How many books are in the Christian Greek Scriptures?", a: "27", options: ["27", "39", "66"], source: "https://wol.jw.org/en/wol/s/r1/lp-e?q=Christian%20Greek%20Scriptures%20twenty-seven%20books" },
    { q: "Who betrayed Jesus?", a: "Judas", options: ["Judas", "Peter", "Thomas"], source: "https://wol.jw.org/en/wol/s/r1/lp-e?q=Judas%20betrayed%20Jesus%20Matthew%2026%3A14" },
    { q: "What was the name of the mountain where Moses received the Ten Commandments?", a: "Sinai", options: ["Sinai", "Zion", "Olivet"], source: "https://wol.jw.org/en/wol/s/r1/lp-e?q=Moses%20Ten%20Commandments%20Mount%20Sinai%20Exodus%2019%3A20" },
    { q: "Who was thrown into a fiery furnace?", a: "Shadrach, Meshach, and Abednego", options: ["Shadrach, Meshach, and Abednego", "Daniel", "Moses"], source: "https://wol.jw.org/en/wol/s/r1/lp-e?q=Shadrach%20Meshach%20Abednego%20fiery%20furnace%20Daniel%203%3A21" },
    { q: "What was the name of the river Jesus was baptized in?", a: "Jordan", options: ["Jordan", "Nile", "Euphrates"], source: "https://wol.jw.org/en/wol/s/r1/lp-e?q=Jesus%20baptized%20Jordan%20Matthew%203%3A13" },
    { q: "Who was the first disciple Jesus called?", a: "Peter", options: ["Peter", "John", "Andrew"], source: "https://wol.jw.org/en/wol/s/r1/lp-e?q=Jesus%20called%20Peter%20first%20disciple%20Matthew%204%3A18" },
    { q: "What was the name of the city where Jesus was nailed and hanged on a stake?", a: "Jerusalem", options: ["Jerusalem", "Bethlehem", "Nazareth"], source: "https://wol.jw.org/en/wol/s/r1/lp-e?q=Jesus%20nailed%20hanged%20stake%20Jerusalem%20Matthew%2027%3A33" },
    { q: "Who was the wisest king of Israel?", a: "Solomon", options: ["Solomon", "David", "Saul"], source: "https://wol.jw.org/en/wol/s/r1/lp-e?q=Solomon%20wisest%20king%201%20Kings%203%3A12" },
    // Added questions (with distinct supporting links on wol.jw.org)
    { q: "How many plagues did Jehovah send upon Egypt?", a: "Ten", options: ["Ten", "Seven", "Twelve"], source: "https://wol.jw.org/en/wol/s/r1/lp-e?q=ten%20plagues%20Egypt%20Exodus" },
    { q: "What was the name of the tree in the middle of the garden of Eden?", a: "Tree of the knowledge of good and bad", options: ["Tree of the knowledge of good and bad", "Tree of life", "Tree of wisdom"], source: "https://wol.jw.org/en/wol/s/r1/lp-e?q=tree%20of%20the%20knowledge%20of%20good%20and%20bad%20Genesis%202%3A9" },
    { q: "How many years did the Israelites wander in the wilderness?", a: "Forty", options: ["Forty", "Thirty", "Fifty"], source: "https://wol.jw.org/en/wol/s/r1/lp-e?q=forty%20years%20wilderness%20Numbers%2014%3A33" },
    { q: "What was the name of the man who helped Jesus carry his torture stake?", a: "Simon", options: ["Simon", "Peter", "John"], source: "https://wol.jw.org/en/wol/s/r1/lp-e?q=Simon%20of%20Cyrene%20carried%20torture%20stake%20Matthew%2027%3A32" },
    { q: "Which prophet was taken to heaven in a chariot of fire?", a: "Elijah", options: ["Elijah", "Elisha", "Isaiah"], source: "https://wol.jw.org/en/wol/s/r1/lp-e?q=chariot%20of%20fire%20Elijah%202%20Kings%202%3A11" },
    { q: "How many days did it take God to create the heavens and the earth?", a: "Six", options: ["Six", "Seven", "Five"], source: "https://wol.jw.org/en/wol/s/r1/lp-e?q=six%20days%20created%20heavens%20earth%20Exodus%2020%3A11" }
  ],
  HARD: [
    { q: "Who was the father of Methuselah?", a: "Enoch", options: ["Lamech", "Enoch", "Jared"], source: "https://wol.jw.org/en/wol/s/r1/lp-e?q=Enoch%20father%20Methuselah%20Genesis%205%3A21" },
    { q: "Where did Paul experience a shipwreck?", a: "Malta", options: ["Crete", "Cyprus", "Malta"], source: "https://wol.jw.org/en/wol/s/r1/lp-e?q=Paul%20shipwreck%20Malta%20Acts%2028%3A1" },
    { q: "Name of the copper serpent Moses made?", a: "Nehushtan", options: ["Nehushtan", "Leviathan", "Behemoth"], source: "https://wol.jw.org/en/wol/s/r1/lp-e?q=copper%20serpent%20Nehushtan%20Numbers%2021%3A9" },
    { q: "Who was the first martyr?", a: "Stephen", options: ["Peter", "James", "Stephen"], source: "https://wol.jw.org/en/wol/s/r1/lp-e?q=Stephen%20first%20martyr%20Acts%207%3A59" },
    { q: "What was the name of the king who had Daniel thrown into the lions' den?", a: "Darius", options: ["Darius", "Nebuchadnezzar", "Belshazzar"], source: "https://wol.jw.org/en/wol/s/r1/lp-e?q=Darius%20Daniel%20lions%27%20den%20Daniel%206%3A16" },
    { q: "What was the name of the high priest who questioned Jesus?", a: "Caiaphas", options: ["Caiaphas", "Annas", "Pilate"], source: "https://wol.jw.org/en/wol/s/r1/lp-e?q=Caiaphas%20high%20priest%20questioned%20Jesus%20Matthew%2026%3A57" },
    { q: "Which book comes before Psalms in the Hebrew-Aramaic Scriptures?", a: "Job", options: ["Job", "Proverbs", "Ecclesiastes"], source: "https://wol.jw.org/en/wol/s/r1/lp-e?q=Job%20before%20Psalms%20Hebrew-Aramaic%20Scriptures" },
    { q: "What was the name of the place where Jesus was transfigured?", a: "Mount of Transfiguration", options: ["Mount of Transfiguration", "Mount Sinai", "Mount Zion"], source: "https://wol.jw.org/en/wol/s/r1/lp-e?q=Jesus%20transfigured%20Matthew%2017%3A1" },
    { q: "Who was the prophet who anointed David as king?", a: "Samuel", options: ["Samuel", "Nathan", "Elijah"], source: "https://wol.jw.org/en/wol/s/r1/lp-e?q=Samuel%20anointed%20David%20king%201%20Samuel%2016%3A13" },
    { q: "What was the name of the Roman governor who sentenced Jesus to death?", a: "Pilate", options: ["Pilate", "Herod", "Caiaphas"], source: "https://wol.jw.org/en/wol/s/r1/lp-e?q=Pilate%20sentenced%20Jesus%20death%20Matthew%2027%3A26" },
    // Added questions (with distinct supporting links on wol.jw.org)
    { q: "What was the name of the valley where David fought Goliath?", a: "Elah", options: ["Elah", "Kidron", "Hinnom"], source: "https://wol.jw.org/en/wol/s/r1/lp-e?q=valley%20of%20Elah%20David%20Goliath%201%20Samuel%2017%3A2" },
    { q: "How many years did Solomon reign as king?", a: "Forty", options: ["Forty", "Thirty", "Fifty"], source: "https://wol.jw.org/en/wol/s/r1/lp-e?q=Solomon%20reigned%20forty%20years%201%20Kings%2011%3A42" },
    { q: "What was the name of the city where Paul was born?", a: "Tarsus", options: ["Tarsus", "Antioch", "Damascus"], source: "https://wol.jw.org/en/wol/s/r1/lp-e?q=Paul%20born%20in%20Tarsus%20Acts%2021%3A39" },
    { q: "What was the name of the man who replaced Judas as an apostle?", a: "Matthias", options: ["Matthias", "Barnabas", "Silas"], source: "https://wol.jw.org/en/wol/s/r1/lp-e?q=Matthias%20replaced%20Judas%20Acts%201%3A26" },
    { q: "What was the name of the mountain where Abraham was told to sacrifice Isaac?", a: "Moriah", options: ["Moriah", "Sinai", "Zion"], source: "https://wol.jw.org/en/wol/s/r1/lp-e?q=land%20of%20Moriah%20Genesis%2022%3A2" }
  ]
};

