import { 
  Wind, Heart, Shield, Crown, Anchor, Star, Sun, MapPin, 
  Dices, Lock, Flame, BookOpen, Sparkles, Zap, CloudRain,
  AlertTriangle, Clock, Gem, Users, Wine, Frown, Briefcase,
  GraduationCap, ShoppingCart, Music, Plane, Cross,
  Eye, MessageCircle, Target, Sword, Scroll,
  Gift, Home, Compass,
  Mountain, Waves, Sunrise, Rainbow, Bird,
  Scissors, Phone, Calendar, Smile, DollarSign, Ban, UserX,
  MessageSquare, XCircle, TrendingUp, ZapOff, ShieldOff
} from 'lucide-react';

export const CHARACTERS_DB = [
  { id: 'moses', name: 'Moses', title: 'The Meekest', ability: 'Lead the Way', desc: 'The first time you Move each turn costs 0 Action Points.', icon: Wind },
  { id: 'ruth', name: 'Ruth', title: 'Loyal Companion', ability: 'Loyal Love', desc: 'You can Help players up to 3 nodes away (Standard is 1).', icon: Heart },
  { id: 'david', name: 'David', title: 'Shepherd King', ability: 'Fearless', desc: 'Add +1 to the Faith Points generated by any Faith Action card.', icon: Shield },
  { id: 'esther', name: 'Esther', title: 'Queen of Persia', ability: 'Royal Favor', desc: 'Draw 1 extra card from Provisions deck at end of turn.', icon: Crown },
  { id: 'noah', name: 'Noah', title: 'Preacher', ability: 'Ark Builder', desc: 'Ignore effects from "Natural Disaster" Trial cards.', icon: Anchor },
  { id: 'abraham', name: 'Abraham', title: 'Father of Faith', ability: 'Friend of God', desc: 'Prayer cards generate +1 extra Faith Point when played.', icon: Star },
  { id: 'sarah', name: 'Sarah', title: 'Joyful Mother', ability: 'Laughter', desc: 'If Unity is 10 at start of turn, gain +1 Action Point.', icon: Sun },
  { id: 'rahab', name: 'Rahab', title: 'Courageous', ability: 'Red Cord', desc: 'Gain +4 Faith Points when securing a Territory (Standard is +2).', icon: MapPin },
  { id: 'gideon', name: 'Gideon', title: 'Mighty Warrior', ability: 'Cautious', desc: 'Once per turn, you may reroll the die on a Faith Action.', icon: Dices },
  { id: 'daniel', name: 'Daniel', title: 'Beloved', ability: 'Integrity', desc: 'Ignore all negative effects from Personal Trial cards.', icon: Lock },
  { id: 'peter', name: 'Peter', title: 'Rock', ability: 'Zeal', desc: 'Once per turn, move 2 nodes distance for 1 Action Point.', icon: Flame },
  { id: 'paul', name: 'Paul', title: 'Apostle', ability: 'Missionary', desc: 'Draw 1 card immediately when entering a new Map Zone.', icon: BookOpen },
];

export const CHALLENGE_POOL = [
  { title: 'Economic Crisis', type: 'Event', category: 'Crisis', req: 11, penalty: 'Unity -1', desc: 'Inflation strikes. Resources are scarce.' },
  { title: 'Direct Opposition', type: 'Event', category: 'Opposition', req: 14, penalty: 'Discard 1 Card', desc: 'Preaching work is restricted.' },
  { title: 'Natural Disaster', type: 'Event', category: 'Disaster', req: 13, penalty: 'Cannot Move 1 Turn', desc: 'Flooding in the area blocks paths.' },
  { title: 'Congregation Dispute', type: 'Event', category: 'Conflict', req: 9, penalty: 'Unity -2', desc: 'Misunderstandings cause friction.' },
  { title: 'Family Opposition', type: 'Event', category: 'Family', req: 10, penalty: 'AP -1 for 2 Turns', desc: 'Relatives pressure a player to stop.' },
  { title: 'Health Emergency', type: 'Event', category: 'Crisis', req: 12, penalty: 'Random Player Frozen', desc: 'A sudden illness strikes.' },
  { title: 'False Accusations', type: 'Event', category: 'Temptation', req: 9, penalty: 'Unity -1', desc: 'Rumors spread. Trust is tested.' },
  { title: 'Resource Shortage', type: 'Event', category: 'Crisis', req: 12, penalty: 'Discard 2 Cards', desc: 'Supplies run low. Hard choices ahead.' },
  { title: 'Internal Conflict', type: 'Event', category: 'Conflict', req: 8, penalty: 'Unity -2', desc: 'Disagreements arise within the group.' },
  { title: 'External Pressure', type: 'Event', category: 'Opposition', req: 13, penalty: 'AP -1 for 2 Turns', desc: 'Outside forces apply pressure.' },
  { title: 'Ministry Obstacle', type: 'Event', category: 'Ministry', req: 12, penalty: 'Discard 1 Card', desc: 'Challenges arise in the preaching work.' },
  { title: 'Service Interruption', type: 'Event', category: 'Ministry', req: 10, penalty: 'Unity -1', desc: 'The ministry work faces setbacks.' },
  { title: 'Communication Breakdown', type: 'Event', category: 'Conflict', req: 9, penalty: 'Cannot Help 1 Turn', desc: 'Misunderstandings block cooperation.' },
  { title: 'Material Temptation', type: 'Event', category: 'Temptation', req: 11, penalty: 'Unity -1', desc: 'Worldly desires distract from the ministry.' },
  { title: 'Persecution Wave', type: 'Event', category: 'Opposition', req: 15, penalty: 'Discard 1 Card', desc: 'Hostility increases dramatically.' },
];

export const CIRCUMSTANCE_POOL = [
  { title: 'Heavy Rains', type: 'Circumstance', effect: 'Move Cost +1', desc: 'Roads are muddy. Moving costs 2 AP.', multiplier: 1.0 },
  { title: 'Digital Surveillance', type: 'Circumstance', effect: 'No Trivia Bonus', desc: 'Communication is monitored. Trivia disabled.', multiplier: 1.0 },
  { title: 'Heatwave', type: 'Circumstance', effect: 'AP Max = 2', desc: 'Exhaustion sets in quickly. Max 2 AP.', multiplier: 1.0 },
  { title: 'Transportation Strike', type: 'Circumstance', effect: 'Range = 0', desc: 'No public transport. Cannot help from distance.', multiplier: 1.0 },
  { title: 'Distractions', type: 'Circumstance', effect: 'No Effect', desc: 'Worldly entertainment distracts.', multiplier: 1.0 },
  { title: 'Economic Hardship', type: 'Circumstance', effect: 'Draw Cost +1', desc: 'Resources are tight. Drawing cards costs 2 AP.', multiplier: 1.0 },
  { title: 'Social Pressure', type: 'Circumstance', effect: 'Help Cost +1', desc: 'Helping others is discouraged. Help action costs 2 AP.', multiplier: 1.0 },
  { title: 'Communication Breakdown', type: 'Circumstance', effect: 'No Help Range', desc: 'Communication is cut off. Cannot help others.', multiplier: 1.0 },
  { title: 'Resource Scarcity', type: 'Circumstance', effect: 'Move Cost +1', desc: 'Fuel and supplies are limited. Moving costs 2 AP.', multiplier: 1.0 },
  { title: 'Increased Opposition', type: 'Circumstance', effect: 'No Trivia Bonus', desc: 'Hostility rises. Trivia bonuses disabled.', multiplier: 1.2 },
  { title: 'Severe Persecution', type: 'Circumstance', effect: 'AP Max = 2', desc: 'Danger increases. Max 2 AP per turn.', multiplier: 1.3 },
  { title: 'Critical Situation', type: 'Circumstance', effect: 'No Effect', desc: 'Pressure mounts.', multiplier: 1.4 },
  { title: 'Extreme Adversity', type: 'Circumstance', effect: 'All Costs +1', desc: 'Everything is harder. All actions cost +1 AP.', multiplier: 1.5 },
  { title: 'Maximum Pressure', type: 'Circumstance', effect: 'No Bonuses', desc: 'The situation is dire. All bonuses disabled.', multiplier: 1.8 },
  { title: 'Ultimate Trial', type: 'Circumstance', effect: 'Double Costs', desc: 'The final test. All action costs doubled.', multiplier: 2.0 },
];

export const SUPPLY_POOL = [
  // FaithAction Cards - Default +1 Faith Point, multipliers: Easy x2, Medium x3, Hard x5
  // Regular FaithAction Cards (15 total)
  { type: 'FaithAction', title: 'Bold Witness', icon: Flame, points: 1, scripture: 'Acts 4:31 - "And when they had made supplication, the place where they were assembled together was shaken, and they were one and all filled with the holy spirit and were speaking the word of God with boldness."' },
  { type: 'FaithAction', title: 'Defend Faith', icon: Shield, points: 1, scripture: '1 Peter 3:15 - "But sanctify the Christ as Lord in your hearts, always ready to make a defense before everyone who demands of you a reason for the hope in you, but doing so with a mild temper and deep respect."' },
  { type: 'FaithAction', title: 'Preach Truth', icon: MessageCircle, points: 1, scripture: '2 Timothy 4:2 - "Preach the word, be at it urgently in favorable times and difficult times, reprove, reprimand, exhort, with all patience and art of teaching."' },
  { type: 'FaithAction', title: 'Stand Firm', icon: Mountain, points: 1, scripture: '1 Corinthians 16:13 - "Keep awake, stand firm in the faith, act like men, grow mighty."' },
  { type: 'FaithAction', title: 'Share Good News', icon: Bird, points: 1, scripture: 'Romans 10:15 - "How will they preach unless they have been sent out? Just as it is written: "How beautiful are the feet of those who declare good news of good things!""' },
  { type: 'FaithAction', title: 'Encourage Others', icon: Users, points: 1, scripture: '1 Thessalonians 5:11 - "So keep encouraging one another and building one another up, just as you are in fact doing."' },
  { type: 'FaithAction', title: 'Teach Scripture', icon: Scroll, points: 1, scripture: '2 Timothy 3:16 - "All Scripture is inspired of God and beneficial for teaching, for reproving, for setting things straight, for disciplining in righteousness."' },
  { type: 'FaithAction', title: 'Show Mercy', icon: Heart, points: 1, scripture: 'Matthew 5:7 - "Happy are the merciful, since they will be shown mercy."' },
  { type: 'FaithAction', title: 'Bear Witness', icon: Eye, points: 1, scripture: 'Acts 1:8 - "But you will receive power when the holy spirit comes upon you, and you will be witnesses of me in Jerusalem, in all Judea and Samaria, and to the most distant part of the earth."' },
  { type: 'FaithAction', title: 'Spread Light', icon: Sunrise, points: 1, scripture: 'Matthew 5:14-16 - "You are the light of the world. A city cannot be hid when located on a mountain. People light a lamp and set it, not under a basket, but on the lampstand, and it shines on all those in the house. Likewise let your light shine before men, that they may see your fine works and give glory to your Father who is in the heavens."' },
  { type: 'FaithAction', title: 'Seek Righteousness', icon: Target, points: 1, scripture: 'Matthew 6:33 - "Keep on, then, seeking first the Kingdom and his righteousness, and all these other things will be added to you."' },
  { type: 'FaithAction', title: 'Fight Evil', icon: Sword, points: 1, scripture: 'Ephesians 6:11 - "Put on the complete suit of armor from God so that you may be able to stand firm against the crafty acts of the Devil."' },
  { type: 'FaithAction', title: 'Build Unity', icon: Home, points: 1, scripture: 'Ephesians 4:3 - "Eagerly maintaining the oneness of the spirit in the uniting bond of peace."' },
  { type: 'FaithAction', title: 'Guide the Lost', icon: Compass, points: 1, scripture: 'Luke 19:10 - "For the Son of man came to seek and to save what was lost."' },
  { type: 'FaithAction', title: 'Proclaim Hope', icon: Rainbow, points: 1, scripture: 'Romans 15:13 - "May the God who gives hope fill you with all joy and peace by your believing, so that you may abound in hope with power of holy spirit."' },
  
  // FaithAction Cards - Remove Trials (Converted from Action cards)
  { type: 'FaithAction', title: 'Reflect', icon: Eye, points: 1, effect: 'If answered correctly: Remove 1 Trial from yourself.', removeTarget: 'self', scripture: 'Psalm 119:15 - "I will meditate on your orders and fix my eyes on your paths."' },
  { type: 'FaithAction', title: 'Encourage', icon: Users, points: 1, effect: 'If answered correctly: Remove 1 Trial from a nearby player (within 1 node).', removeTarget: 'other', scripture: '1 Thessalonians 5:11 - "So keep encouraging one another and building one another up, just as you are in fact doing."' },
  { type: 'FaithAction', title: 'Pray Together', icon: Cross, points: 1, effect: 'If answered correctly: Remove 1 Trial from a nearby player (within 1 node).', removeTarget: 'other', scripture: 'Matthew 18:19 - "Again I say to you, if two of you on earth agree about anything they ask for, it will be done for them by my Father in heaven."' },
  { type: 'FaithAction', title: 'Share Scripture', icon: Scroll, points: 1, effect: 'If answered correctly: Remove 1 Trial from yourself.', removeTarget: 'self', scripture: 'Hebrews 4:12 - "For the word of God is alive and active and sharper than any two-edged sword."' },
  
  // FaithAction Cards - Remove Bad Qualities (New set)
  { type: 'FaithAction', title: 'Practice Humility', icon: Wind, points: 1, effect: 'If answered correctly: Remove 1 Bad Quality from yourself.', removeTarget: 'self', removeType: 'BadQuality', scripture: 'Philippians 2:3 - "Do nothing out of contentiousness or out of egotism, but with humility consider others superior to you."' },
  { type: 'FaithAction', title: 'Show Gratitude', icon: Gift, points: 1, effect: 'If answered correctly: Remove 1 Bad Quality from yourself.', removeTarget: 'self', removeType: 'BadQuality', scripture: '1 Thessalonians 5:18 - "In everything give thanks, for this is the will of God in Christ Jesus for you."' },
  { type: 'FaithAction', title: 'Exercise Self-Control', icon: Lock, points: 1, effect: 'If answered correctly: Remove 1 Bad Quality from yourself.', removeTarget: 'self', removeType: 'BadQuality', scripture: 'Galatians 5:23 - "...self-control..."' },
  { type: 'FaithAction', title: 'Practice Generosity', icon: Heart, points: 1, effect: 'If answered correctly: Remove 1 Bad Quality from yourself.', removeTarget: 'self', removeType: 'BadQuality', scripture: 'Acts 20:35 - "There is more happiness in giving than there is in receiving."' },
  { type: 'FaithAction', title: 'Show Respect', icon: Users, points: 1, effect: 'If answered correctly: Remove 1 Bad Quality from yourself.', removeTarget: 'self', removeType: 'BadQuality', scripture: '1 Peter 2:17 - "Honor men of all sorts, have love for the whole association of brothers."' },
  { type: 'FaithAction', title: 'Practice Loyalty', icon: Anchor, points: 1, effect: 'If answered correctly: Remove 1 Bad Quality from yourself.', removeTarget: 'self', removeType: 'BadQuality', scripture: 'Proverbs 3:3 - "Do not let loyal love and faithfulness leave you. Tie them around your neck; write them on the tablet of your heart."' },
  { type: 'FaithAction', title: 'Show Natural Affection', icon: Heart, points: 1, effect: 'If answered correctly: Remove 1 Bad Quality from yourself.', removeTarget: 'self', removeType: 'BadQuality', scripture: 'Romans 12:10 - "In brotherly love have tender affection for one another."' },
  { type: 'FaithAction', title: 'Practice Moderation', icon: Target, points: 1, effect: 'If answered correctly: Remove 1 Bad Quality from yourself.', removeTarget: 'self', removeType: 'BadQuality', scripture: 'Philippians 4:5 - "Let your reasonableness become known to all men."' },
  
  // Prayer Cards - 4 Types with Multiple Scripture Variations
  // Each card: +1 Faith Point (default)
  // Combinations (consume 1 AP): 2 cards = better, 3 cards = better, 4 cards = best
  
  // Praise (6 variations)
  { type: 'Prayer', prayerType: 'Praise', title: 'Praise', icon: Crown, points: 1, effect: '+1 Faith Point', scripture: 'Psalm 150:6 - "Let everything that breathes praise Jah. Praise Jah, you people!"' },
  { type: 'Prayer', prayerType: 'Praise', title: 'Praise', icon: Crown, points: 1, effect: '+1 Faith Point', scripture: 'Psalm 100:4 - "Enter into his gates with thanksgiving, into his courtyards with praise. Give thanks to him, bless his name."' },
  { type: 'Prayer', prayerType: 'Praise', title: 'Praise', icon: Crown, points: 1, effect: '+1 Faith Point', scripture: 'Psalm 34:1 - "I will praise Jehovah at all times; his praise will constantly be in my mouth."' },
  { type: 'Prayer', prayerType: 'Praise', title: 'Praise', icon: Crown, points: 1, effect: '+1 Faith Point', scripture: 'Revelation 19:5 - "Praise our God, all you his slaves, you who fear him, the small ones and the great."' },
  { type: 'Prayer', prayerType: 'Praise', title: 'Praise', icon: Crown, points: 1, effect: '+1 Faith Point', scripture: 'Psalm 145:2 - "Every day I will praise you, and I will extol your name forever and ever."' },
  { type: 'Prayer', prayerType: 'Praise', title: 'Praise', icon: Crown, points: 1, effect: '+1 Faith Point', scripture: 'Psalm 103:1 - "Bless Jehovah, O my soul, and all that is within me, bless his holy name."' },
  
  // Thanksgiving (6 variations)
  { type: 'Prayer', prayerType: 'Thanksgiving', title: 'Thanksgiving', icon: Gift, points: 1, effect: '+1 Faith Point', scripture: '1 Thessalonians 5:18 - "In everything give thanks, for this is the will of God in Christ Jesus for you."' },
  { type: 'Prayer', prayerType: 'Thanksgiving', title: 'Thanksgiving', icon: Gift, points: 1, effect: '+1 Faith Point', scripture: 'Philippians 4:6 - "Do not be anxious over anything, but in everything by prayer and supplication along with thanksgiving, let your petitions be made known to God."' },
  { type: 'Prayer', prayerType: 'Thanksgiving', title: 'Thanksgiving', icon: Gift, points: 1, effect: '+1 Faith Point', scripture: 'Psalm 107:1 - "Give thanks to Jehovah, for he is good; his loyal love endures forever."' },
  { type: 'Prayer', prayerType: 'Thanksgiving', title: 'Thanksgiving', icon: Gift, points: 1, effect: '+1 Faith Point', scripture: 'Colossians 3:15 - "Also, let the peace of the Christ rule in your hearts, for you were called to that peace in one body. And be thankful."' },
  { type: 'Prayer', prayerType: 'Thanksgiving', title: 'Thanksgiving', icon: Gift, points: 1, effect: '+1 Faith Point', scripture: 'Psalm 136:1 - "Give thanks to Jehovah, for he is good, for his loyal love endures forever."' },
  { type: 'Prayer', prayerType: 'Thanksgiving', title: 'Thanksgiving', icon: Gift, points: 1, effect: '+1 Faith Point', scripture: 'Ephesians 5:20 - "Always giving thanks to our God and Father for everything in the name of our Lord Jesus Christ."' },
  
  // Petitions (6 variations)
  { type: 'Prayer', prayerType: 'Petitions', title: 'Petitions', icon: Heart, points: 1, effect: '+1 Faith Point', scripture: 'Matthew 7:7 - "Keep on asking, and it will be given you; keep on seeking, and you will find; keep on knocking, and it will be opened to you."' },
  { type: 'Prayer', prayerType: 'Petitions', title: 'Petitions', icon: Heart, points: 1, effect: '+1 Faith Point', scripture: 'James 5:16 - "Therefore, openly confess your sins to one another and pray for one another, so that you may be healed. A righteous man\'s supplication has a powerful effect."' },
  { type: 'Prayer', prayerType: 'Petitions', title: 'Petitions', icon: Heart, points: 1, effect: '+1 Faith Point', scripture: '1 John 5:14 - "And this is the confidence that we have toward him, that no matter what we ask according to his will, he hears us."' },
  { type: 'Prayer', prayerType: 'Petitions', title: 'Petitions', icon: Heart, points: 1, effect: '+1 Faith Point', scripture: 'Luke 11:9 - "So I say to you, keep on asking, and it will be given you; keep on seeking, and you will find; keep on knocking, and it will be opened to you."' },
  { type: 'Prayer', prayerType: 'Petitions', title: 'Petitions', icon: Heart, points: 1, effect: '+1 Faith Point', scripture: 'Mark 11:24 - "That is why I tell you, all the things you pray and ask for, have faith that you have received them, and you will have them."' },
  { type: 'Prayer', prayerType: 'Petitions', title: 'Petitions', icon: Heart, points: 1, effect: '+1 Faith Point', scripture: 'Jeremiah 29:12 - "You will call me and come and pray to me, and I will listen to you."' },
  
  // Supplications (6 variations)
  { type: 'Prayer', prayerType: 'Supplications', title: 'Supplications', icon: Cross, points: 1, effect: '+1 Faith Point', scripture: 'Hebrews 5:7 - "During his life on earth, Christ offered up supplications and also petitions, with strong outcries and tears, to the One who was able to save him out of death, and he was favorably heard."' },
  { type: 'Prayer', prayerType: 'Supplications', title: 'Supplications', icon: Cross, points: 1, effect: '+1 Faith Point', scripture: 'Ephesians 6:18 - "Carry on prayer on every occasion in spirit, and to that end keep awake with all constancy and with supplication in behalf of all the holy ones."' },
  { type: 'Prayer', prayerType: 'Supplications', title: 'Supplications', icon: Cross, points: 1, effect: '+1 Faith Point', scripture: 'Philippians 4:6 - "Do not be anxious over anything, but in everything by prayer and supplication along with thanksgiving, let your petitions be made known to God."' },
  { type: 'Prayer', prayerType: 'Supplications', title: 'Supplications', icon: Cross, points: 1, effect: '+1 Faith Point', scripture: '1 Timothy 2:1 - "First of all, then, I urge that supplications, prayers, intercessions, and thanksgiving be made concerning all sorts of men."' },
  { type: 'Prayer', prayerType: 'Supplications', title: 'Supplications', icon: Cross, points: 1, effect: '+1 Faith Point', scripture: 'Psalm 28:2 - "Listen to my voice when I call to you for help, when I raise my hands in prayer toward your holy sanctuary."' },
  { type: 'Prayer', prayerType: 'Supplications', title: 'Supplications', icon: Cross, points: 1, effect: '+1 Faith Point', scripture: 'Daniel 9:3 - "I turned my face to Jehovah the true God, to seek him with prayer and with supplications, along with fasting and sackcloth and ashes."' },
  // Good Qualities - Fruitage of the Spirit (Galatians 5:22-23) - 9 total
  { type: 'Quality', title: 'Love', icon: Heart, points: 0, effect: 'Active: Helping Range +1. Immune to "Family Emergency". Scripture: Galatians 5:22', immuneToObligations: ['Family Emergency'], scripture: 'Galatians 5:22 - "On the other hand, the fruitage of the spirit is love..."' },
  { type: 'Quality', title: 'Joy', icon: Smile, points: 0, effect: 'Active: Ignore "Discouragement" trials. Draw 1 extra card at end of turn. Scripture: Galatians 5:22', scripture: 'Galatians 5:22 - "...joy..."' },
  { type: 'Quality', title: 'Peace', icon: Bird, points: 0, effect: 'Active: Ignore Unity penalties from challenges. +1 Unity when you help others. Scripture: Galatians 5:22', scripture: 'Galatians 5:22 - "...peace..."' },
  { type: 'Quality', title: 'Patience', icon: Clock, points: 0, effect: 'Active: +1 AP per turn. Ignore movement restrictions. Immune to work obligations. Scripture: Galatians 5:22', immuneToObligations: ['Overtime Shift', 'Work Deadline'], scripture: 'Galatians 5:22 - "...patience..."' },
  { type: 'Quality', title: 'Kindness', icon: Gift, points: 0, effect: 'Active: Help action costs 0 AP once per turn. Scripture: Galatians 5:22', scripture: 'Galatians 5:22 - "...kindness..."' },
  { type: 'Quality', title: 'Goodness', icon: Star, points: 0, effect: 'Active: +1 Faith Point when contributing to challenges. Scripture: Galatians 5:22', scripture: 'Galatians 5:22 - "...goodness..."' },
  { type: 'Quality', title: 'Faith', icon: Cross, points: 0, effect: 'Active: Ignore "Doubt" trials. Prayer cards generate +1 extra point. Immune to "Final Exams". Scripture: Galatians 5:22', immuneToObligations: ['Final Exams'], scripture: 'Galatians 5:22 - "...faith..."' },
  { type: 'Quality', title: 'Mildness', icon: Wind, points: 0, effect: 'Active: Ignore Unity penalties from "Dispute" challenges. Scripture: Galatians 5:23', scripture: 'Galatians 5:23 - "...mildness..."' },
  { type: 'Quality', title: 'Self-Control', icon: Lock, points: 0, effect: 'Active: Ignore "Materialism" and "Worldly Distraction" trials. Immune to recreation obligations. Scripture: Galatians 5:23', immuneToObligations: ['Recreation Time', 'Social Obligation', 'Vacation Trip'], scripture: 'Galatians 5:23 - "...self-control..."' },
  
  // Bad Qualities - 2 Timothy 3:1-5 - Core Set (9 cards)
  { type: 'BadQuality', title: 'Lovers of Themselves', icon: Users, points: -1, effect: 'Burden: Cannot help others. Discard 1 card to remove.', scripture: '2 Timothy 3:2 - "For men will be lovers of themselves..."' },
  { type: 'BadQuality', title: 'Lovers of Money', icon: DollarSign, points: -1, effect: 'Burden: Territory bonuses disabled. Discard 1 card to remove.', scripture: '2 Timothy 3:2 - "...lovers of money..."' },
  { type: 'BadQuality', title: 'Boastful', icon: Crown, points: -2, effect: 'Burden: Cannot use bonus points. Discard 1 card to remove.', scripture: '2 Timothy 3:2 - "...boastful..."' },
  { type: 'BadQuality', title: 'Haughty', icon: Gem, points: -1, effect: 'Burden: Discard 1 card to remove.', scripture: '2 Timothy 3:2 - "...haughty..."' },
  { type: 'BadQuality', title: 'Blasphemers', icon: MessageSquare, points: -2, effect: 'Burden: Cannot use Prayer cards. Discard 1 card to remove.', scripture: '2 Timothy 3:2 - "...blasphemers..."' },
  { type: 'BadQuality', title: 'Disobedient to Parents', icon: AlertTriangle, points: -1, effect: 'Burden: Movement costs +1 AP. Discard 1 card to remove.', scripture: '2 Timothy 3:2 - "...disobedient to parents..."' },
  { type: 'BadQuality', title: 'Unthankful', icon: Frown, points: -1, effect: 'Burden: Cannot receive help from others. Discard 1 card to remove.', scripture: '2 Timothy 3:2 - "...unthankful..."' },
  { type: 'BadQuality', title: 'Disloyal', icon: Flame, points: -2, effect: 'Burden: Cannot contribute to challenges. Discard 1 card to remove.', scripture: '2 Timothy 3:2 - "...disloyal..."' },
  { type: 'BadQuality', title: 'Having No Natural Affection', icon: UserX, points: -2, effect: 'Burden: Cannot use Help action. Discard 1 card to remove.', scripture: '2 Timothy 3:3 - "...having no natural affection..."' },
  { type: 'Trial', title: 'Doubt', icon: CloudRain, points: -2, effect: 'Burden: Cannot use Bonus Points.' },
  { type: 'Trial', title: 'Anxiety', icon: AlertTriangle, points: -1, effect: 'Burden: Movement costs 2 AP.' },
  { type: 'Trial', title: 'Unwise Use of Time', icon: Clock, points: -1, effect: 'Burden: Max 2 AP per turn. Discard 1 card to remove.' },
  { type: 'Trial', title: 'Showy Display', icon: Gem, points: -1, effect: 'Burden: Territory bonuses are disabled for you.' },
  { type: 'Trial', title: 'Bad Associations', icon: Users, points: -2, effect: 'Burden: You cannot use the Help action.' },
  { type: 'Trial', title: 'Overdrinking', icon: Wine, points: -1, effect: 'Burden: Start next turn with -1 AP.' },
  { type: 'Trial', title: 'Materialism', icon: Frown, points: -1, effect: 'Burden: Move 1 Zone Outward if possible at start of turn.' },
  { type: 'Trial', title: 'Fear', icon: AlertTriangle, points: -1, effect: 'Burden: Cannot move. Discard 1 card to remove.' },
  { type: 'Trial', title: 'Discouragement', icon: CloudRain, points: -1, effect: 'Burden: Discard 1 card to remove this trial.' },
  { type: 'Trial', title: 'Pride', icon: Gem, points: -2, effect: 'Burden: Cannot help others. Discard 1 card to remove.' },
  { type: 'Trial', title: 'Selfishness', icon: Frown, points: -1, effect: 'Burden: Discard 1 card to remove.' },
  { type: 'Trial', title: 'Worldly Distraction', icon: Music, points: -1, effect: 'Burden: Cannot use bonus points from cards.' },
  { type: 'Obligation', title: 'Overtime Shift', icon: Briefcase, targetNode: 'trap_work', desc: 'Teleport to Workplace. Turn Ends.' },
  { type: 'Obligation', title: 'Final Exams', icon: GraduationCap, targetNode: 'trap_school', desc: 'Teleport to University. Turn Ends.' },
  { type: 'Obligation', title: 'Grocery Run', icon: ShoppingCart, targetNode: 'trap_market', desc: 'Teleport to Supermarket. Turn Ends.' },
  { type: 'Obligation', title: 'Recreation Time', icon: Music, targetNode: 'trap_recreation', desc: 'Teleport to Recreation. Leaving reduces Faith Progress.' },
  { type: 'Obligation', title: 'Vacation Trip', icon: Plane, targetNode: 'trap_vacation', desc: 'Teleport to Vacation. Next Territory move costs +1 AP.' },
  { type: 'Obligation', title: 'Family Emergency', icon: Heart, targetNode: 'trap_home', desc: 'Teleport to Home. Discard 1 card.' },
  { type: 'Obligation', title: 'Work Deadline', icon: Briefcase, targetNode: 'trap_work', desc: 'Teleport to Workplace. Start next turn with -1 AP.' },
  { type: 'Obligation', title: 'Social Obligation', icon: Users, targetNode: 'trap_recreation', desc: 'Teleport to Recreation. Cannot help others this turn.' },
  
];

